/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.

using System.Linq;
using Oci.Common.Waiters;
using Oci.MarketplaceprivateofferService.Models;
using Oci.MarketplaceprivateofferService.Requests;
using Oci.MarketplaceprivateofferService.Responses;

namespace Oci.MarketplaceprivateofferService
{
    /// <summary>
    /// Contains collection of helper methods to produce Oci.Common.Waiters for different resources of OfferQuote.
    /// </summary>
    public class OfferQuoteWaiters
    {
        private readonly OfferQuoteClient client;

        public  OfferQuoteWaiters(OfferQuoteClient client)
        {
            this.client = client;
        }

        /// <summary>
        /// Creates a waiter using default wait configuration.
        /// </summary>
        /// <param name="request">Request to send.</param>
        /// <param name="targetStates">Desired resource states. If multiple states are provided then the waiter will return once the resource reaches any of the provided states</param>
        /// <returns>a new Oci.common.Waiter instance</returns>
        public Waiter<GetOfferQuoteRequest, GetOfferQuoteResponse> ForOfferQuote(GetOfferQuoteRequest request, params OfferQuote.LifecycleStateEnum[] targetStates)
        {
            return this.ForOfferQuote(request, WaiterConfiguration.DefaultWaiterConfiguration, targetStates);
        }

        /// <summary>
        /// Creates a waiter using the provided configuration.
        /// </summary>
        /// <param name="request">Request to send.</param>
        /// <param name="config">Wait Configuration</param>
        /// <param name="targetStates">Desired resource states. If multiple states are provided then the waiter will return once the resource reaches any of the provided states</param>
        /// <returns>a new Oci.common.Waiter instance</returns>
        public Waiter<GetOfferQuoteRequest, GetOfferQuoteResponse> ForOfferQuote(GetOfferQuoteRequest request, WaiterConfiguration config, params OfferQuote.LifecycleStateEnum[] targetStates)
        {
            var agent = new WaiterAgent<GetOfferQuoteRequest, GetOfferQuoteResponse>(
                request,
                request => client.GetOfferQuote(request),
                response => targetStates.Contains(response.OfferQuote.LifecycleState.Value),
                targetStates.Contains(OfferQuote.LifecycleStateEnum.Deleted)
            );
            return new Waiter<GetOfferQuoteRequest, GetOfferQuoteResponse>(config, agent);
        }
    }
}
