/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.DatascienceService.Models
{
    /// <summary>
    /// The compute target instance configuration details for managed compute cluster type compute target.
    /// </summary>
    public class ManagedComputeClusterInstanceConfigurationDetails 
    {
        
        /// <value>
        /// The shape used to launch the instances in compute target. Supported shapes can be retrieved using compute target shapes api.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "InstanceShape is required.")]
        [JsonProperty(PropertyName = "instanceShape")]
        public string InstanceShape { get; set; }
        
        /// <value>
        /// The size of the boot volume to attach to the instance.
        /// </value>
        [JsonProperty(PropertyName = "bootVolumeSizeInGBs")]
        public System.Nullable<int> BootVolumeSizeInGBs { get; set; }
        
        [JsonProperty(PropertyName = "instanceShapeDetails")]
        public ManagedComputeClusterInstanceShapeDetails InstanceShapeDetails { get; set; }
        
    }
}
