/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.DatascienceService.Models
{
    /// <summary>
    /// The interval schedule trigger.
    /// </summary>
    public class ScheduleIntervalTrigger : ScheduleTrigger
    {
                ///
        /// <value>
        /// The type of frequency
        /// </value>
        ///
        public enum FrequencyEnum {
            /// This value is used if a service returns a value for this enum that is not recognized by this version of the SDK.
            [EnumMember(Value = null)]
            UnknownEnumValue,
            [EnumMember(Value = "HOURLY")]
            Hourly,
            [EnumMember(Value = "DAILY")]
            Daily
        };

        /// <value>
        /// The type of frequency
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "Frequency is required.")]
        [JsonProperty(PropertyName = "frequency")]
        [JsonConverter(typeof(Oci.Common.Utils.ResponseEnumConverter))]
        public System.Nullable<FrequencyEnum> Frequency { get; set; }
        
        /// <value>
        /// The interval of frequency.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "Interval is required.")]
        [JsonProperty(PropertyName = "interval")]
        public System.Nullable<int> Interval { get; set; }
        
        /// <value>
        /// Maximum number of minutes after timeStart that the scheduler may use to randomly select the first execution time.
        /// This value is considered only when isRandomStartTime is true.
        /// This value applies only to the initial execution; subsequent executions remain deterministic based on the resolved first trigger time.
        /// If timeStart is null, the service resolves the effective start time using the current time.
        /// The initial jitter window is then applied once to that resolved start time to determine the first execution time.
        /// If not provided and isRandomStartTime is true, the service defaults the jitter window to half of the configured interval duration.
        /// The value must not exceed the configured interval duration.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "initialJitterInMinutes")]
        public System.Nullable<int> InitialJitterInMinutes { get; set; }
        
        /// <value>
        /// when true, system generates a randomized first start time between timeStart and timeStart + initialJitterInMinutes.
        /// if timeStart is null, the current time is used as the base start time.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "isRandomStartTime")]
        public System.Nullable<bool> IsRandomStartTime { get; set; }
        
        [JsonProperty(PropertyName = "triggerType")]
        private readonly string triggerType = "INTERVAL";
    }
}
