/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace Oci.DatascienceService.Models
{
    /// <summary>
    /// The target scaling configuration for the workload scaling.
    /// </summary>
    [JsonConverter(typeof(TargetScalingConfigurationModelConverter))]
    public class TargetScalingConfiguration 
    {
                ///
        /// <value>
        /// The metric at which the alarm used to trigger autoscaling actions for workload.
        /// </value>
        ///
        public enum TargetScalingConfigurationTypeEnum {
            [EnumMember(Value = "THRESHOLD")]
            Threshold,
            [EnumMember(Value = "QUERY")]
            Query
        };

        
    }

    public class TargetScalingConfigurationModelConverter : JsonConverter
    {
        private static NLog.Logger logger = NLog.LogManager.GetCurrentClassLogger();
        public override bool CanWrite => false;
        public override bool CanRead => true;
        public override bool CanConvert(System.Type type)
        {
            return type == typeof(TargetScalingConfiguration);
        }
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            throw new System.InvalidOperationException("Use default serialization.");
        }

        public override object ReadJson(JsonReader reader, System.Type objectType, object existingValue, JsonSerializer serializer)
        {
            var jsonObject = JObject.Load(reader);
            var obj = default(TargetScalingConfiguration);
            var discriminator = jsonObject["targetScalingConfigurationType"].Value<string>();
            switch (discriminator)
            {
                case "QUERY":
                    obj = new TargetCustomExpressionQueryScalingConfiguration();
                    break;
                case "THRESHOLD":
                    obj = new TargetPredefinedExpressionThresholdScalingConfiguration();
                    break;
            }
            if (obj != null)
            {
                serializer.Populate(jsonObject.CreateReader(), obj);
            }
            else
            {
                logger.Warn($"The type {discriminator} is not present under TargetScalingConfiguration! Returning null value.");
            }
            return obj;
        }
    }
}
