/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.DatascienceService.Models
{
    /// <summary>
    /// The scaling configuration for the custom expression query for the workload.
    /// </summary>
    public class TargetCustomExpressionQueryScalingConfiguration : TargetScalingConfiguration
    {
        
        /// <value>
        /// The Monitoring Query Language (MQL) expression to evaluate for the alarm. The Alarms feature of the Monitoring service
        /// interprets results for each returned time series as Boolean values, where zero represents false and a non-zero value
        /// represents true. A true value means that the trigger rule condition has been met. The query must specify a metric,
        /// statistic, interval, and trigger rule (threshold or absence). Supported values for interval: 1m-60m (also 1h).
        /// You can optionally specify dimensions and grouping functions. Supported grouping functions: grouping(), groupBy().
        /// Example of threshold alarm:
        ///   ```
        ///   CPUUtilization[1m]{resourceId = \"Model_Deployment_OCID\"}.grouping().mean() < 25
        ///   CPUUtilization[1m]{resourceId = \"Model_Deployment_OCID\"}.grouping().mean() > 75
        ///   ```
        /// 
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "Query is required.")]
        [JsonProperty(PropertyName = "query")]
        public string Query { get; set; }
        
        /// <value>
        /// A metric value at which the scaling operation will be triggered.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "Threshold is required.")]
        [JsonProperty(PropertyName = "threshold")]
        public System.Nullable<float> Threshold { get; set; }
        
        /// <value>
        /// Namespace to read the metrics from. Default value will be service metric namespace.
        /// </value>
        [JsonProperty(PropertyName = "metricNamespace")]
        public string MetricNamespace { get; set; }
        
        [JsonProperty(PropertyName = "targetScalingConfigurationType")]
        private readonly string targetScalingConfigurationType = "QUERY";
    }
}
