/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.GoldengateService.Models
{
    /// <summary>
    /// Summary of OCI Generative AI authentication details for an AI Model connection.
    /// 
    /// </summary>
    public class OciGenAiModelAuthDetailsSummary : AiModelAuthDetailsSummary
    {
        
        /// <value>
        /// API key secret OCID for the AI model connection.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "apiKeySecretId")]
        public string ApiKeySecretId { get; set; }
        
        /// <value>
        /// OCI Generative AI key fingerprint.
        /// 
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "KeyFingerprint is required.")]
        [JsonProperty(PropertyName = "keyFingerprint")]
        public string KeyFingerprint { get; set; }
        
        /// <value>
        /// The name of the region. e.g.: us-ashburn-1
        /// If the region is not provided, backend will default to the default region.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "region")]
        public string Region { get; set; }
        
        /// <value>
        /// OCI Generative AI tenancy OCID. If this value is not provided, or is updated to an empty
        /// value, it defaults to the tenancy OCID of the user who is executing the operation.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "tenancyId")]
        public string TenancyId { get; set; }
        
        /// <value>
        /// OCI Generative AI user OCID. If this value is not provided, or is updated to an empty
        /// value, it defaults to the OCID of the user who is executing the operation.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "userId")]
        public string UserId { get; set; }
        
        [JsonProperty(PropertyName = "authType")]
        private readonly string authType = "OCI_GEN_AI";
    }
}
