/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Oci.FunctionsService.Models;

namespace Oci.FunctionsService.Requests
{
    /// <example>
    /// Click <a href="https://docs.oracle.com/en-us/iaas/tools/dot-net-examples/latest/functions/ListFunctionsRuntimeVersions.cs.html">here</a> to see an example of how to use ListFunctionsRuntimeVersions request.
    /// </example>
    public class ListFunctionsRuntimeVersionsRequest : Oci.Common.IOciRequest
    {
        
        /// <value>
        /// unique FunctionsRuntime identifier
        /// </value>
        [Oci.Common.Http.HttpConverter(Oci.Common.Http.TargetEnum.Query, "functionsRuntimeId")]
        public string FunctionsRuntimeId { get; set; }
        
        /// <value>
        /// A filter to return only resources that match the entire FunctionsRuntime name given.
        /// </value>
        [Oci.Common.Http.HttpConverter(Oci.Common.Http.TargetEnum.Query, "functionsRuntimeName")]
        public string FunctionsRuntimeName { get; set; }
        
        /// <value>
        /// unique FunctionsRuntimeVersion identifier
        /// </value>
        [Oci.Common.Http.HttpConverter(Oci.Common.Http.TargetEnum.Query, "functionsRuntimeVersionId")]
        public string FunctionsRuntimeVersionId { get; set; }
        
        /// <value>
        /// A filter to return only resources that match the entire FunctionsRuntimeVersion name given.
        /// </value>
        [Oci.Common.Http.HttpConverter(Oci.Common.Http.TargetEnum.Query, "displayName")]
        public string DisplayName { get; set; }
        
        /// <value>
        /// A filter to return only resources that match the entire osVersion name given.
        /// </value>
        [Oci.Common.Http.HttpConverter(Oci.Common.Http.TargetEnum.Query, "osVersion")]
        public string OsVersion { get; set; }
        
        /// <value>
        /// A filter to return only resources that match the entire languageVersion name given.
        /// </value>
        [Oci.Common.Http.HttpConverter(Oci.Common.Http.TargetEnum.Query, "languageVersion")]
        public string LanguageVersion { get; set; }
        
        /// <value>
        /// Matches the current version associated with a FunctionsRuntime.
        /// 
        /// </value>
        [Oci.Common.Http.HttpConverter(Oci.Common.Http.TargetEnum.Query, "isCurrentVersion")]
        public System.Nullable<bool> IsCurrentVersion { get; set; }
        
        /// <value>
        /// A filter to return only resources their lifecycleState matches the given lifecycleState.
        /// </value>
        [Oci.Common.Http.HttpConverter(Oci.Common.Http.TargetEnum.Query, "lifecycleState")]
        public System.Nullable<FunctionsRuntimeVersion.LifecycleStateEnum> LifecycleState { get; set; }
        
        ///
        /// <value>
        /// The field to sort by. Only one sort order may be provided. Default order for timeCreated is descending. Default order for name is ascending.
        /// 
        /// </value>
        ///
        public enum SortByEnum {
            [EnumMember(Value = "timeCreated")]
            TimeCreated,
            [EnumMember(Value = "name")]
            Name
        };

        /// <value>
        /// The field to sort by. Only one sort order may be provided. Default order for timeCreated is descending. Default order for name is ascending.
        /// 
        /// </value>
        [Oci.Common.Http.HttpConverter(Oci.Common.Http.TargetEnum.Query, "sortBy")]
        public System.Nullable<SortByEnum> SortBy { get; set; }
        
        /// <value>
        /// The maximum number of items to return. 1 is the minimum, 50 is the maximum.
        /// <br/>
        /// Default: 10
        /// 
        /// </value>
        [Oci.Common.Http.HttpConverter(Oci.Common.Http.TargetEnum.Query, "limit")]
        public System.Nullable<int> Limit { get; set; }
        
        /// <value>
        /// The pagination token for a list query returned by a previous operation
        /// 
        /// </value>
        [Oci.Common.Http.HttpConverter(Oci.Common.Http.TargetEnum.Query, "page")]
        public string Page { get; set; }
        
        ///
        /// <value>
        /// Specifies sort order.
        /// <br/>
        /// * **ASC:** Ascending sort order.
        /// * **DESC:** Descending sort order.
        /// 
        /// </value>
        ///
        public enum SortOrderEnum {
            [EnumMember(Value = "ASC")]
            Asc,
            [EnumMember(Value = "DESC")]
            Desc
        };

        /// <value>
        /// Specifies sort order.
        /// <br/>
        /// * **ASC:** Ascending sort order.
        /// * **DESC:** Descending sort order.
        /// 
        /// </value>
        [Oci.Common.Http.HttpConverter(Oci.Common.Http.TargetEnum.Query, "sortOrder")]
        public System.Nullable<SortOrderEnum> SortOrder { get; set; }
        
        /// <value>
        /// The unique Oracle-assigned identifier for the request. If you need to contact Oracle about a
        /// particular request, please provide the request ID.
        /// 
        /// </value>
        [Oci.Common.Http.HttpConverter(Oci.Common.Http.TargetEnum.Header, "opc-request-id")]
        public string OpcRequestId { get; set; }
    }
}
