/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.GenerativeaiService.Models
{
    /// <summary>
    /// Defines a configurable parameter supported by a model.
    /// </summary>
    public class Parameter 
    {
        
        /// <value>
        /// The name of this parameter.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "Name is required.")]
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }
        
        /// <value>
        /// The data type of the parameter (e.g., float, integer, string).
        /// </value>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }
        
        /// <value>
        /// The minimum allowed value for this parameter. Applicable only when type is FLOAT or INTEGER.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "minimum")]
        public System.Double Minimum { get; set; }
        
        /// <value>
        /// The maximum allowed value for this parameter. Applicable only when type is FLOAT or INTEGER.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "maximum")]
        public System.Double Maximum { get; set; }
        
        /// <value>
        /// The default value used when this parameter is not supplied.
        /// </value>
        [JsonProperty(PropertyName = "defaultValue")]
        public string DefaultValue { get; set; }
        
        /// <value>
        /// A human-readable description of this parameter.
        /// </value>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }
        
    }
}
