/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace Oci.Distributeddatabasev26Service.Models
{
    /// <summary>
    /// Details of the catalog database associated with the Globally distributed autonomous database.
    /// </summary>
    [JsonConverter(typeof(DistributedAutonomousDatabaseCatalogDatabaseModelConverter))]
    public class DistributedAutonomousDatabaseCatalogDatabase 
    {
                ///
        /// <value>
        /// The source of the Globally distributed autonomous database type.
        /// Use ADBD_EXISTING_CLUSTER for an autonomous database on Dedicated Infrastructure that uses a pre-existing cluster.
        /// 
        /// </value>
        ///
        public enum SourceEnum {
            [EnumMember(Value = "ADBD_EXISTING_CLUSTER")]
            AdbdExistingCluster
        };

        
        /// <value>
        /// The name of the catalog.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "Name is required.")]
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }
        
        /// <value>
        /// The time the catalog was created. An RFC3339 formatted datetime string.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "TimeCreated is required.")]
        [JsonProperty(PropertyName = "timeCreated")]
        public System.Nullable<System.DateTime> TimeCreated { get; set; }
        
        /// <value>
        /// The time the catalog was last updated. An RFC3339 formatted datetime string.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "TimeUpdated is required.")]
        [JsonProperty(PropertyName = "timeUpdated")]
        public System.Nullable<System.DateTime> TimeUpdated { get; set; }
        
        [JsonProperty(PropertyName = "metadata")]
        public DistributedAutonomousDbMetadata Metadata { get; set; }
        
    }

    public class DistributedAutonomousDatabaseCatalogDatabaseModelConverter : JsonConverter
    {
        private static NLog.Logger logger = NLog.LogManager.GetCurrentClassLogger();
        public override bool CanWrite => false;
        public override bool CanRead => true;
        public override bool CanConvert(System.Type type)
        {
            return type == typeof(DistributedAutonomousDatabaseCatalogDatabase);
        }
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            throw new System.InvalidOperationException("Use default serialization.");
        }

        public override object ReadJson(JsonReader reader, System.Type objectType, object existingValue, JsonSerializer serializer)
        {
            var jsonObject = JObject.Load(reader);
            var obj = default(DistributedAutonomousDatabaseCatalogDatabase);
            var discriminator = jsonObject["source"].Value<string>();
            switch (discriminator)
            {
                case "ADBD_EXISTING_CLUSTER":
                    obj = new DistributedAutonomousDatabaseCatalogWithDedicatedInfra();
                    break;
            }
            if (obj != null)
            {
                serializer.Populate(jsonObject.CreateReader(), obj);
            }
            else
            {
                logger.Warn($"The type {discriminator} is not present under DistributedAutonomousDatabaseCatalogDatabase! Returning null value.");
            }
            return obj;
        }
    }
}
