/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.Distributeddatabasev26Service.Models
{
    /// <summary>
    /// One move RU invocation record for the Globally distributed autonomous database.
    /// </summary>
    public class DistributedAutonomousDatabaseRuChangeLogSummary 
    {
        
        /// <value>
        /// Source shard for move RU invocation.
        /// </value>
        [JsonProperty(PropertyName = "sourceShardName")]
        public string SourceShardName { get; set; }
        
        /// <value>
        /// Target shard for move RU invocation.
        /// </value>
        [JsonProperty(PropertyName = "targetShardName")]
        public string TargetShardName { get; set; }
        
        /// <value>
        /// Replication unit identifier associated with the invocation.
        /// </value>
        [JsonProperty(PropertyName = "ruId")]
        public string RuId { get; set; }
                ///
        /// <value>
        /// Current or terminal status of the move RU invocation.
        /// </value>
        ///
        public enum StatusEnum {
            /// This value is used if a service returns a value for this enum that is not recognized by this version of the SDK.
            [EnumMember(Value = null)]
            UnknownEnumValue,
            [EnumMember(Value = "FAILED")]
            Failed,
            [EnumMember(Value = "QUEUED")]
            Queued,
            [EnumMember(Value = "IN_PROGRESS")]
            InProgress,
            [EnumMember(Value = "COMPLETED")]
            Completed
        };

        /// <value>
        /// Current or terminal status of the move RU invocation.
        /// </value>
        [JsonProperty(PropertyName = "status")]
        [JsonConverter(typeof(Oci.Common.Utils.ResponseEnumConverter))]
        public System.Nullable<StatusEnum> Status { get; set; }
        
        /// <value>
        /// Actor who triggered the move RU invocation.
        /// </value>
        [JsonProperty(PropertyName = "triggeredBy")]
        public string TriggeredBy { get; set; }
        
        /// <value>
        /// Entry creation timestamp in UTC.
        /// </value>
        [JsonProperty(PropertyName = "timeCreated")]
        public System.Nullable<System.DateTime> TimeCreated { get; set; }
        
        /// <value>
        /// Entry update timestamp in UTC.
        /// </value>
        [JsonProperty(PropertyName = "timeUpdated")]
        public System.Nullable<System.DateTime> TimeUpdated { get; set; }
        
    }
}
