/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.Distributeddatabasev26Service.Models
{
    /// <summary>
    /// Details of a distributed autonomous database shard on dedicated infrastructure.
    /// </summary>
    public class DistributedAutonomousDatabaseShardWithDedicatedInfra : DistributedAutonomousDatabaseShardDatabase
    {
        
        /// <value>
        /// The compute count for the shard database. It has to be in multiples of 2.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "ComputeCount is required.")]
        [JsonProperty(PropertyName = "computeCount")]
        public System.Nullable<float> ComputeCount { get; set; }
        
        /// <value>
        /// The data disk group size to be allocated in GBs for the shard database.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "DataStorageSizeInGbs is required.")]
        [JsonProperty(PropertyName = "dataStorageSizeInGbs")]
        public System.Double DataStorageSizeInGbs { get; set; }
        
        /// <value>
        /// Indicates if vertical auto scaling is enabled for the Autonomous AI Database CPU core count.
        /// The default value is `FALSE`.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "isAutoScalingEnabled")]
        public System.Nullable<bool> IsAutoScalingEnabled { get; set; }
        
        /// <value>
        /// The [OCID](https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the cloud Autonomous Exadata VM Cluster.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "CloudAutonomousVmClusterId is required.")]
        [JsonProperty(PropertyName = "cloudAutonomousVmClusterId")]
        public string CloudAutonomousVmClusterId { get; set; }
        
        /// <value>
        /// The [OCID](https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the Oracle Cloud Infrastructure [vault](https://docs.oracle.com/iaas/Content/KeyManagement/Concepts/keyoverview.htm#concepts). This parameter and `kmsKeyId` are required for Customer Managed Keys.
        /// </value>
        [JsonProperty(PropertyName = "vaultId")]
        public string VaultId { get; set; }
        
        /// <value>
        /// The [OCID](https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the key container that is used as the master encryption key in database transparent data encryption (TDE) operations.
        /// </value>
        [JsonProperty(PropertyName = "kmsKeyId")]
        public string KmsKeyId { get; set; }
        
        /// <value>
        /// The [OCID](https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the key container version that is used in database transparent data encryption (TDE) operations KMS Key can have multiple key versions.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "kmsKeyVersionId")]
        public string KmsKeyVersionId { get; set; }
        
        /// <value>
        /// The [OCID](https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the key store used to create the shard.
        /// </value>
        [JsonProperty(PropertyName = "okvKeyStoreId")]
        public string OkvKeyStoreId { get; set; }
        
        /// <value>
        /// The OKV endpoint name.
        /// </value>
        [JsonProperty(PropertyName = "okvEndPointGroupName")]
        public string OkvEndPointGroupName { get; set; }
        
        /// <value>
        /// The protection mode for the shard peer.
        /// </value>
        [JsonProperty(PropertyName = "protectionMode")]
        [JsonConverter(typeof(Oci.Common.Utils.ResponseEnumConverter))]
        public System.Nullable<DistributedAutonomousDbProtectionMode> ProtectionMode { get; set; }
        
        /// <value>
        /// The lag time preference based on data loss tolerance in seconds.
        /// </value>
        [JsonProperty(PropertyName = "fastStartFailOverLagLimitInSeconds")]
        public System.Nullable<int> FastStartFailOverLagLimitInSeconds { get; set; }
        
        /// <value>
        /// The scheduling detail for the quarterly maintenance window of the standby Autonomous Container Database.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "standbyMaintenanceBufferInDays")]
        public System.Nullable<int> StandbyMaintenanceBufferInDays { get; set; }
                ///
        /// <value>
        /// Status of the distributed autonomous database shard.
        /// </value>
        ///
        public enum StatusEnum {
            /// This value is used if a service returns a value for this enum that is not recognized by this version of the SDK.
            [EnumMember(Value = null)]
            UnknownEnumValue,
            [EnumMember(Value = "FAILED")]
            Failed,
            [EnumMember(Value = "DELETING")]
            Deleting,
            [EnumMember(Value = "DELETED")]
            Deleted,
            [EnumMember(Value = "UPDATING")]
            Updating,
            [EnumMember(Value = "CREATING")]
            Creating,
            [EnumMember(Value = "CREATED")]
            Created,
            [EnumMember(Value = "READY_FOR_CONFIGURATION")]
            ReadyForConfiguration,
            [EnumMember(Value = "CONFIGURED")]
            Configured,
            [EnumMember(Value = "NEEDS_ATTENTION")]
            NeedsAttention
        };

        /// <value>
        /// Status of the distributed autonomous database shard.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "Status is required.")]
        [JsonProperty(PropertyName = "status")]
        [JsonConverter(typeof(Oci.Common.Utils.ResponseEnumConverter))]
        public System.Nullable<StatusEnum> Status { get; set; }
        
        /// <value>
        /// the identifier of the underlying supporting resource.
        /// </value>
        [JsonProperty(PropertyName = "supportingResourceId")]
        public string SupportingResourceId { get; set; }
        
        /// <value>
        /// the identifier of the container database for underlying supporting resource.
        /// </value>
        [JsonProperty(PropertyName = "containerDatabaseId")]
        public string ContainerDatabaseId { get; set; }
        
        [JsonProperty(PropertyName = "source")]
        private readonly string source = "ADBD_EXISTING_CLUSTER";
    }
}
