/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.Distributeddatabasev26Service.Models
{
    /// <summary>
    /// Payload to rotate passwords for shards and catalogs in the Globally distributed autonomous database.
    /// 
    /// </summary>
    public class RotateDistributedAutonomousDatabasePasswordsDetails 
    {
        
        /// <value>
        /// Collection of shard or catalog password rotation details.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "DatabaseDetails is required.")]
        [JsonProperty(PropertyName = "databaseDetails")]
        public System.Collections.Generic.List<RotateDistributedAutonomousDatabaseDetails> DatabaseDetails { get; set; }
        
    }
}
