/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.Distributeddatabasev26Service.Models
{
    /// <summary>
    /// Distributed database user shard space details.
    /// </summary>
    public class UserShardSpace 
    {
        
        /// <value>
        /// The name of user shard space. 
        /// It must start with a letter and contain only letters, digits, and underscores. 
        /// Maximum length is 40 characters.
        /// 
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "Name is required.")]
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }
        
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "OriginalReplica is required.")]
        [JsonProperty(PropertyName = "originalReplica")]
        public UserShardSpaceReplica OriginalReplica { get; set; }
        
        /// <value>
        /// The details of data guard replica for the user shard space.
        /// </value>
        [JsonProperty(PropertyName = "dataGuardReplicas")]
        public System.Collections.Generic.List<UserShardSpaceReplica> DataGuardReplicas { get; set; }
        
    }
}
