/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.AdmService.Models
{
    /// <summary>
    /// Vulnerable artifact version range.
    /// </summary>
    public class VulnerableArtifactVersionRange 
    {
        
        /// <value>
        /// The version immediately after the last affected version. Versions up to, but not including this version, are vulnerable.
        /// </value>
        [JsonProperty(PropertyName = "versionEndExcluding")]
        public string VersionEndExcluding { get; set; }
        
        /// <value>
        /// Marks the latest version that is affected by the vulnerability. This version and all preceding versions, going back to versionStartExcluding or versionStartIncluding, are considered vulnerable.
        /// </value>
        [JsonProperty(PropertyName = "versionEndIncluding")]
        public string VersionEndIncluding { get; set; }
        
        /// <value>
        /// The first version affected by the vulnerability. This version and those following it are considered vulnerable until versionEndExcluding or versionEndIncluding is reached.
        /// </value>
        [JsonProperty(PropertyName = "versionStartIncluding")]
        public string VersionStartIncluding { get; set; }
        
        /// <value>
        /// The version immediately before the start of affected versions. The specified version is not affected, but versions immediately after are, up to versionStartIncluding or beyond, if not otherwise defined.
        /// </value>
        [JsonProperty(PropertyName = "versionStartExcluding")]
        public string VersionStartExcluding { get; set; }
        
    }
}
