/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.SelfService.Models
{
    /// <summary>
    /// A metered usage dimension associated with a usage-based or hybrid pricing plan.
    /// </summary>
    public class UsageDimension 
    {
        
        /// <value>
        /// The name of the usage dimension.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "DimensionName is required.")]
        [JsonProperty(PropertyName = "dimensionName")]
        public string DimensionName { get; set; }
        
        /// <value>
        /// The stable key used internally to map this usage dimension to billing details.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "DimensionKey is required.")]
        [JsonProperty(PropertyName = "dimensionKey")]
        public string DimensionKey { get; set; }
        
        /// <value>
        /// A detailed explanation of the usage dimension.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "DimensionDescription is required.")]
        [JsonProperty(PropertyName = "dimensionDescription")]
        public string DimensionDescription { get; set; }
        
        /// <value>
        /// The metric type in which usage is measured.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "MetricType is required.")]
        [JsonProperty(PropertyName = "metricType")]
        [JsonConverter(typeof(Oci.Common.Utils.ResponseEnumConverter))]
        public System.Nullable<MetricType> MetricType { get; set; }
        
        /// <value>
        /// Specifies the interval at which the usage dimension is billed.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "DimensionBillingFrequency is required.")]
        [JsonProperty(PropertyName = "dimensionBillingFrequency")]
        [JsonConverter(typeof(Oci.Common.Utils.ResponseEnumConverter))]
        public System.Nullable<BillingFrequency> DimensionBillingFrequency { get; set; }
        
        /// <value>
        /// Quantity included in the base fee for hybrid plans.
        /// </value>
        [JsonProperty(PropertyName = "includedQuantity")]
        public System.Nullable<float> IncludedQuantity { get; set; }
        
        /// <value>
        /// Dimension-level rates in various supported currencies.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "Rates is required.")]
        [JsonProperty(PropertyName = "rates")]
        public System.Collections.Generic.List<PricingRate> Rates { get; set; }
        
    }
}
