/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.GenerativeaiinferenceService.Models
{
    /// <summary>
    /// A category with its score.
    /// </summary>
    public class CategoryScore 
    {
        
        /// <value>
        /// The name of the category.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "Name is required.")]
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }
        
        /// <value>
        /// The score of the category.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "Score is required.")]
        [JsonProperty(PropertyName = "score")]
        public System.Double Score { get; set; }
                ///
        ///
        public enum FlaggedModalitiesEnum {
            /// This value is used if a service returns a value for this enum that is not recognized by this version of the SDK.
            [EnumMember(Value = null)]
            UnknownEnumValue,
            [EnumMember(Value = "TEXT")]
            Text,
            [EnumMember(Value = "IMAGE")]
            Image
        };

        /// <value>
        /// The input modalities flagged by this category score. Present only when the request is
        /// processed using a non-empty `multimodalInput`.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "flaggedModalities", ItemConverterType = typeof(Oci.Common.Utils.ResponseEnumConverter))]
        public System.Collections.Generic.List<FlaggedModalitiesEnum> FlaggedModalities { get; set; }
        
    }
}
