/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.GenerativeaiinferenceService.Models
{
    /// <summary>
    /// Details of a guardrail version.
    /// </summary>
    public class GuardrailVersion 
    {
        
        /// <value>
        /// The guardrail system version string, e.g., \"1.0.0\"
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "GuardrailVersionProp is required.")]
        [JsonProperty(PropertyName = "guardrailVersion")]
        public string GuardrailVersionProp { get; set; }
                ///
        /// <value>
        /// The state of the guardrail version.
        /// </value>
        ///
        public enum StateEnum {
            /// This value is used if a service returns a value for this enum that is not recognized by this version of the SDK.
            [EnumMember(Value = null)]
            UnknownEnumValue,
            [EnumMember(Value = "ACTIVE")]
            Active,
            [EnumMember(Value = "PREVIEW")]
            Preview,
            [EnumMember(Value = "DEPRECATED")]
            Deprecated,
            [EnumMember(Value = "RETIRED")]
            Retired
        };

        /// <value>
        /// The state of the guardrail version.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "State is required.")]
        [JsonProperty(PropertyName = "state")]
        [JsonConverter(typeof(Oci.Common.Utils.ResponseEnumConverter))]
        public System.Nullable<StateEnum> State { get; set; }
        
        /// <value>
        /// The preview date of the guardrail version.
        /// </value>
        [JsonProperty(PropertyName = "timePreviewed")]
        public System.Nullable<System.DateTime> TimePreviewed { get; set; }
        
        /// <value>
        /// The activation date of the guardrail version.
        /// </value>
        [JsonProperty(PropertyName = "timeActivated")]
        public System.Nullable<System.DateTime> TimeActivated { get; set; }
        
        /// <value>
        /// The deprecated date of the guardrail version.
        /// </value>
        [JsonProperty(PropertyName = "timeDeprecated")]
        public System.Nullable<System.DateTime> TimeDeprecated { get; set; }
        
        /// <value>
        /// The retired date of the guardrail version.
        /// </value>
        [JsonProperty(PropertyName = "timeRetired")]
        public System.Nullable<System.DateTime> TimeRetired { get; set; }
        
        /// <value>
        /// The description of the guardrail version.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "Description is required.")]
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }
        
    }
}
