/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.TenantmanagercontrolplaneService.Models
{
    /// <summary>
    /// Result of a query request for a list of link features. Contains LinkFeature items.
    /// </summary>
    public class LinkFeatureSummary 
    {
        
        /// <value>
        /// The feature associated with this link. Default value is CORE.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "Feature is required.")]
        [JsonProperty(PropertyName = "feature")]
        public string Feature { get; set; }
        
        /// <value>
        /// Display name of the feature.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "DisplayName is required.")]
        [JsonProperty(PropertyName = "displayName")]
        public string DisplayName { get; set; }
        
        /// <value>
        /// Description of the feature.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "Description is required.")]
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }
        
        /// <value>
        /// ConsoleUrl of the feature.
        /// </value>
        [JsonProperty(PropertyName = "partnerServiceConsoleUrl")]
        public string PartnerServiceConsoleUrl { get; set; }
        
        /// <value>
        /// UserGuideUrl of the feature.
        /// </value>
        [JsonProperty(PropertyName = "userGuideUrl")]
        public string UserGuideUrl { get; set; }
        
    }
}
