/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.RecoveryService.Models
{
    /// <summary>
    /// Describes the parameters required to create an on demand long term backup.
    /// </summary>
    public class CreateLongTermBackupDetails 
    {
        
        /// <value>
        /// A user provided name for the long term backup. The 'displayName' does not have to be unique, and it can be modified. Avoid entering confidential information.
        /// </value>
        [JsonProperty(PropertyName = "displayName")]
        public string DisplayName { get; set; }
        
        /// <value>
        /// The OCID of the protected database for which you want to create the long-term backup.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "ProtectedDatabaseId is required.")]
        [JsonProperty(PropertyName = "protectedDatabaseId")]
        public string ProtectedDatabaseId { get; set; }
        
        /// <value>
        /// The desired target point (SCN) at which you want to create the long-term backup of the database.For example, specify the value as 1000 if you want to create the long-term backup until SCN 1000. If you want to specify the target point as a time expression instead of the SCN value, then use the longTermRetentionPointInTime parameter.
        /// </value>
        [JsonProperty(PropertyName = "retentionScn")]
        public System.Nullable<int> RetentionScn { get; set; }
        
        /// <value>
        /// An RFC3339 formatted datetime string that indicates the desired target point in time in the database at which you want to create the long-term backup. For example, if you want the long-term backup to include all the changes until May 22 at 9:10 PM, then specify the value as, '2020-05-22T21:10:00.000Z'. If you want to specify the target point as an SCN value instead of the target time, then use the databaseSCN parameter.
        /// </value>
        [JsonProperty(PropertyName = "retentionPointInTime")]
        public System.Nullable<System.DateTime> RetentionPointInTime { get; set; }
        
        /// <value>
        /// The maximum period to retain the long-term backup. Specify the retention period type and the duration for the long-term backup. If you have chosen the retention period type as 'DAYS', then specify a duration ranging from 90 days to 3650 days. If you have chosen the retention period type as 'YEARS', then specify a duration ranging from 1 year to 10 years.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "RetentionPeriod is required.")]
        [JsonProperty(PropertyName = "retentionPeriod")]
        public System.Collections.Generic.List<RetentionPeriodValue> RetentionPeriod { get; set; }
        
        /// <value>
        /// Simple key-value pair that is applied without any predefined name, type or scope. Exists for cross-compatibility only.
        /// Example: {&quot;bar-key&quot;: &quot;value&quot;}
        /// </value>
        [JsonProperty(PropertyName = "freeformTags")]
        public System.Collections.Generic.Dictionary<string, string> FreeformTags { get; set; }
        
        /// <value>
        /// Defined tags for this resource. Each key is predefined and scoped to a namespace.
        /// Example: {&quot;foo-namespace&quot;: {&quot;bar-key&quot;: &quot;value&quot;}}. For more information, see [Resource Tags](https://docs.oracle.com/en-us/iaas/Content/General/Concepts/resourcetags.htm)
        /// </value>
        [JsonProperty(PropertyName = "definedTags")]
        public System.Collections.Generic.Dictionary<string, System.Collections.Generic.Dictionary<string, System.Object>> DefinedTags { get; set; }
        
    }
}
