/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.RecoveryService.Models
{
    /// <summary>
    /// The details of a Long Term Backup.
    /// 
    /// </summary>
    public class LongTermBackup 
    {
        
        /// <value>
        /// The OCID of the long-term backup.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "Id is required.")]
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }
        
        /// <value>
        /// The user-provided name for the long-term backup. You can change the displayName. Avoid entering confidential information.
        /// </value>
        [JsonProperty(PropertyName = "displayName")]
        public string DisplayName { get; set; }
        
        /// <value>
        /// The OCID of the compartment containing the long-term backup.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "CompartmentId is required.")]
        [JsonProperty(PropertyName = "compartmentId")]
        public string CompartmentId { get; set; }
        
        /// <value>
        /// The OCID of the protected database associated with the long-term backup.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "ProtectedDatabaseId is required.")]
        [JsonProperty(PropertyName = "protectedDatabaseId")]
        public string ProtectedDatabaseId { get; set; }
        
        /// <value>
        /// The unique system change number (SCN) or the target point in the database until which the long-term backup is consistent.
        /// </value>
        [JsonProperty(PropertyName = "retentionScn")]
        public System.Nullable<int> RetentionScn { get; set; }
        
        /// <value>
        /// An RFC3339 formatted datetime string that indicates the target point in time until which the long-term backup is consistent. For example, '2020-05-22T21:10:29.600Z'.
        /// </value>
        [JsonProperty(PropertyName = "retentionPointInTime")]
        public System.Nullable<System.DateTime> RetentionPointInTime { get; set; }
        
        /// <value>
        /// An RFC3339 formatted datetime string that indicates the time when the long-term backup was created. For example, '2020-05-22T21:10:29.600Z'.
        /// </value>
        [JsonProperty(PropertyName = "timeBackupInitiated")]
        public System.Nullable<System.DateTime> TimeBackupInitiated { get; set; }
        
        /// <value>
        /// An RFC3339 formatted datetime string that indicates the time when the long-term backup completed. For example, '2020-05-22T21:10:29.600Z'.
        /// </value>
        [JsonProperty(PropertyName = "timeBackupCompleted")]
        public System.Nullable<System.DateTime> TimeBackupCompleted { get; set; }
        
        /// <value>
        /// The maximum number of DAYS or YEARS to store the long-term backup. You can retain a long-term backup for a period ranging from 90-3650 days or 1-10 years.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "RetentionPeriod is required.")]
        [JsonProperty(PropertyName = "retentionPeriod")]
        public System.Collections.Generic.List<RetentionPeriodValue> RetentionPeriod { get; set; }
        
        /// <value>
        /// Indicates that Recovery Service must retain the backup for the specified long-term retention period.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "RetentionUntilDateTime is required.")]
        [JsonProperty(PropertyName = "retentionUntilDateTime")]
        public System.Nullable<System.DateTime> RetentionUntilDateTime { get; set; }
        
        /// <value>
        /// The Oracle Database ID, which identifies an Oracle Database located outside of Oracle Cloud.
        /// </value>
        [JsonProperty(PropertyName = "databaseIdentifier")]
        public string DatabaseIdentifier { get; set; }
        
        /// <value>
        /// The size of the database, in gigabytes.
        /// </value>
        [JsonProperty(PropertyName = "databaseSizeInGBs")]
        public System.Nullable<int> DatabaseSizeInGBs { get; set; }
        
        /// <value>
        /// An RFC3339 formatted datetime string that indicates the time when the long-term backup was created. For Example: '2020-05-22T21:10:29.600Z'.
        /// </value>
        [JsonProperty(PropertyName = "timeCreated")]
        public System.Nullable<System.DateTime> TimeCreated { get; set; }
        
        /// <value>
        /// An RFC3339 formatted datetime string that indicates the time when the long term backup was last updated. For Example: '2020-05-22T21:10:29.600Z'.
        /// </value>
        [JsonProperty(PropertyName = "timeUpdated")]
        public System.Nullable<System.DateTime> TimeUpdated { get; set; }
                ///
        /// <value>
        /// The current state of the long term backup.
        /// 
        /// </value>
        ///
        public enum LifecycleStateEnum {
            /// This value is used if a service returns a value for this enum that is not recognized by this version of the SDK.
            [EnumMember(Value = null)]
            UnknownEnumValue,
            [EnumMember(Value = "CREATING")]
            Creating,
            [EnumMember(Value = "UPDATING")]
            Updating,
            [EnumMember(Value = "ACTIVE")]
            Active,
            [EnumMember(Value = "DELETING")]
            Deleting,
            [EnumMember(Value = "DELETED")]
            Deleted,
            [EnumMember(Value = "FAILED")]
            Failed,
            [EnumMember(Value = "CANCELING")]
            Canceling,
            [EnumMember(Value = "CANCELED")]
            Canceled
        };

        /// <value>
        /// The current state of the long term backup.
        /// 
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "LifecycleState is required.")]
        [JsonProperty(PropertyName = "lifecycleState")]
        [JsonConverter(typeof(Oci.Common.Utils.ResponseEnumConverter))]
        public System.Nullable<LifecycleStateEnum> LifecycleState { get; set; }
                ///
        /// <value>
        /// More details on the state of the backup when it is in Creating lifecycleState.
        /// 
        /// </value>
        ///
        public enum LifecycleSubstateEnum {
            /// This value is used if a service returns a value for this enum that is not recognized by this version of the SDK.
            [EnumMember(Value = null)]
            UnknownEnumValue,
            [EnumMember(Value = "WAITING_FOR_BACKUP_FROM_DB")]
            WaitingForBackupFromDb,
            [EnumMember(Value = "SCHEDULED_FOR_ARCHIVAL")]
            ScheduledForArchival,
            [EnumMember(Value = "ARCHIVAL_IN_PROGRESS")]
            ArchivalInProgress
        };

        /// <value>
        /// More details on the state of the backup when it is in Creating lifecycleState.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "lifecycleSubstate")]
        [JsonConverter(typeof(Oci.Common.Utils.ResponseEnumConverter))]
        public System.Nullable<LifecycleSubstateEnum> LifecycleSubstate { get; set; }
        
        /// <value>
        /// A detailed message about the current lifecycle state of the long-term backup. For example, it can be used to provide actionable information for a resource in a Failed state.
        /// </value>
        [JsonProperty(PropertyName = "lifecycleDetails")]
        public string LifecycleDetails { get; set; }
        
        /// <value>
        /// Recovery Manager (RMAN) assigned unique identifier for the long-term backup.
        /// </value>
        [JsonProperty(PropertyName = "rmanTag")]
        public string RmanTag { get; set; }
        
        /// <value>
        /// Simple key-value pair that is applied without any predefined name, type or scope. Exists for cross-compatibility only.
        /// Example: {&quot;bar-key&quot;: &quot;value&quot;}
        /// </value>
        [JsonProperty(PropertyName = "freeformTags")]
        public System.Collections.Generic.Dictionary<string, string> FreeformTags { get; set; }
        
        /// <value>
        /// Defined tags for this resource. Each key is predefined and scoped to a namespace.
        /// Example: {&quot;foo-namespace&quot;: {&quot;bar-key&quot;: &quot;value&quot;}}. For more information, see [Resource Tags](https://docs.oracle.com/en-us/iaas/Content/General/Concepts/resourcetags.htm)
        /// </value>
        [JsonProperty(PropertyName = "definedTags")]
        public System.Collections.Generic.Dictionary<string, System.Collections.Generic.Dictionary<string, System.Object>> DefinedTags { get; set; }
        
        /// <value>
        /// Usage of system tag keys. These predefined keys are scoped to namespaces.
        /// Example: {&quot;orcl-cloud&quot;: {&quot;free-tier-retained&quot;: &quot;true&quot;}}. For more information, see [Resource Tags](https://docs.oracle.com/en-us/iaas/Content/General/Concepts/resourcetags.htm)
        /// </value>
        [JsonProperty(PropertyName = "systemTags")]
        public System.Collections.Generic.Dictionary<string, System.Collections.Generic.Dictionary<string, System.Object>> SystemTags { get; set; }
        
    }
}
