/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;

namespace Oci.GenerativeaidataService.Models
{
  /// <summary>
  /// Controls whether GenerateSqlFromNl, ExecuteSql, or Query waits for execution to finish or submits background execution.
  /// </summary>
  public enum CompletionMode {
      [EnumMember(Value = "WAIT_FOR_COMPLETION")]
      WaitForCompletion,
      [EnumMember(Value = "BACKGROUND_JOB")]
      BackgroundJob
  }
}
