/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.GenerativeaidataService.Models
{
    /// <summary>
    /// A DeltaRefreshEnrichmentJobConfiguration is an EnrichmentJobConfiguration [indicated by the first item under `allOf`, which is a reference to EnrichmentJobConfiguration]
    /// that describes the database schema that will be the scope of the delta refresh enrichment job. As distinguished by enrichmentJobType [with specific characteristics defined by the second item under `allOf`].
    /// deltaRefreshSchedule is optional, is not used by the service, and is retained only for backward compatibility. It should be treated as deprecated.
    /// 
    /// </summary>
    public class DeltaRefreshEnrichmentJobConfiguration : EnrichmentJobConfiguration
    {
        
        /// <value>
        /// Name of the DB Schema to be enriched
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "SchemaName is required.")]
        [JsonProperty(PropertyName = "schemaName")]
        public string SchemaName { get; set; }
        
        /// <value>
        /// Deprecated schedule for occurrences of Delta Refresh jobs. This value is not used by the service.
        /// </value>
        [JsonProperty(PropertyName = "deltaRefreshSchedule")]
        public System.Object DeltaRefreshSchedule { get; set; }
        
        [JsonProperty(PropertyName = "enrichmentJobType")]
        private readonly string enrichmentJobType = "DELTA_REFRESH";
    }
}
