/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.ClusterhealthService.Models
{
    /// <summary>
    /// Query filters for retrieving diagnosis summaries.
    /// </summary>
    public class QueryDiagnosisSummaryDetails 
    {
        
        /// <value>
        /// A list of instance OCIDs to match.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "InstanceIds is required.")]
        [JsonProperty(PropertyName = "instanceIds")]
        public System.Collections.Generic.List<string> InstanceIds { get; set; }
                ///
        /// <value>
        /// The test type, PASSIVE or ACTIVE
        /// </value>
        ///
        public enum TestTypeEnum {
            [EnumMember(Value = "PASSIVE")]
            Passive,
            [EnumMember(Value = "ACTIVE")]
            Active
        };

        /// <value>
        /// The test type, PASSIVE or ACTIVE
        /// </value>
        [JsonProperty(PropertyName = "testType")]
        [JsonConverter(typeof(StringEnumConverter))]
        public System.Nullable<TestTypeEnum> TestType { get; set; }
        
        /// <value>
        /// Start of the time range for tests run, in RFC 3339 format.
        /// </value>
        [JsonProperty(PropertyName = "timeTestRunIntervalStart")]
        public System.Nullable<System.DateTime> TimeTestRunIntervalStart { get; set; }
        
        /// <value>
        /// End of the time range for tests run, in RFC 3339 format.
        /// </value>
        [JsonProperty(PropertyName = "timeTestRunIntervalEnd")]
        public System.Nullable<System.DateTime> TimeTestRunIntervalEnd { get; set; }
        
    }
}
