/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace Oci.DatabasetoolsruntimeService.Models
{
    /// <summary>
    /// The content of a Database Tools database API gateway config API spec sub resource to be created.
    /// </summary>
    [JsonConverter(typeof(CreateDatabaseToolsDatabaseApiGatewayConfigPoolApiSpecDetailsModelConverter))]
    public class CreateDatabaseToolsDatabaseApiGatewayConfigPoolApiSpecDetails 
    {
        
        
        /// <value>
        /// A user-friendly name. Does not have to be unique, and it\u2019s changeable. Avoid entering confidential information.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "DisplayName is required.")]
        [JsonProperty(PropertyName = "displayName")]
        public string DisplayName { get; set; }
        
        /// <value>
        /// The content of a string-escaped Open API spec in JSON format.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "Content is required.")]
        [JsonProperty(PropertyName = "content")]
        public string Content { get; set; }
        
    }

    public class CreateDatabaseToolsDatabaseApiGatewayConfigPoolApiSpecDetailsModelConverter : JsonConverter
    {
        public override bool CanWrite => false;
        public override bool CanRead => true;
        public override bool CanConvert(System.Type type)
        {
            return type == typeof(CreateDatabaseToolsDatabaseApiGatewayConfigPoolApiSpecDetails);
        }
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            throw new System.InvalidOperationException("Use default serialization.");
        }

        public override object ReadJson(JsonReader reader, System.Type objectType, object existingValue, JsonSerializer serializer)
        {
            var jsonObject = JObject.Load(reader);
            var obj = default(CreateDatabaseToolsDatabaseApiGatewayConfigPoolApiSpecDetails);
            var discriminator = jsonObject["type"].Value<string>();
            switch (discriminator)
            {
                case "DEFAULT":
                    obj = new CreateDatabaseToolsDatabaseApiGatewayConfigPoolApiSpecDefaultDetails();
                    break;
            }
            serializer.Populate(jsonObject.CreateReader(), obj);
            return obj;
        }
    }
}
