/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.DatabasetoolsruntimeService.Models
{
    /// <summary>
    /// The content of a Database Tools database API gateway config global resource.
    /// </summary>
    public class DatabaseToolsDatabaseApiGatewayConfigContent 
    {
        
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "Global is required.")]
        [JsonProperty(PropertyName = "global")]
        public DatabaseToolsDatabaseApiGatewayConfigGlobal Global { get; set; }
        
        /// <value>
        /// The content of the Database Tools database API gateway config pools each with API spec and auto API spec definitions.
        /// </value>
        [JsonProperty(PropertyName = "pools")]
        public System.Collections.Generic.List<DatabaseToolsDatabaseApiGatewayConfigPoolContent> Pools { get; set; }
        
    }
}
