/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.DatabasetoolsruntimeService.Models
{
    /// <summary>
    /// The certificate bundle that describes the SSL certicicate files.
    /// </summary>
    public class DatabaseApiGatewayConfigCertificateBundleFileName : DatabaseApiGatewayConfigCertificateBundle
    {
        
        [JsonProperty(PropertyName = "certificatePublic")]
        public DatabaseApiGatewayConfigCertificatePublicFileName CertificatePublic { get; set; }
        
        [JsonProperty(PropertyName = "certificatePrivateKey")]
        public DatabaseApiGatewayConfigCertificatePrivateKeyFileName CertificatePrivateKey { get; set; }
        
        [JsonProperty(PropertyName = "type")]
        private readonly string type = "FILENAME";
    }
}
