/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace Oci.DatabasetoolsruntimeService.Models
{
    /// <summary>
    /// The content of a Database Tools database API gateway config global resource.
    /// </summary>
    [JsonConverter(typeof(DatabaseToolsDatabaseApiGatewayConfigGlobalModelConverter))]
    public class DatabaseToolsDatabaseApiGatewayConfigGlobal 
    {
        
        /// <value>
        /// A string that uniquely identifies a Database Tools database API gateway config global settings resource.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "Key is required.")]
        [JsonProperty(PropertyName = "key")]
        public string Key { get; set; }
        
                ///
        /// <value>
        /// How the target pool route value is determined for a HTTP request.
        /// </value>
        ///
        public enum PoolRouteEnum {
            [EnumMember(Value = "PATH")]
            Path,
            [EnumMember(Value = "HEADER")]
            Header
        };

        /// <value>
        /// How the target pool route value is determined for a HTTP request.
        /// </value>
        [JsonProperty(PropertyName = "poolRoute")]
        [JsonConverter(typeof(Oci.Common.Utils.ResponseEnumConverter))]
        public System.Nullable<PoolRouteEnum> PoolRoute { get; set; }
        
        /// <value>
        /// The request header name providing the pool route value.
        /// </value>
        [JsonProperty(PropertyName = "poolRoutingHeader")]
        public string PoolRoutingHeader { get; set; }
                ///
        /// <value>
        /// ORDS database API is a database management and monitoring REST API. Database Actions requires this feature.
        /// </value>
        ///
        public enum DatabaseApiStatusEnum {
            [EnumMember(Value = "ENABLED")]
            Enabled,
            [EnumMember(Value = "DISABLED")]
            Disabled
        };

        /// <value>
        /// ORDS database API is a database management and monitoring REST API. Database Actions requires this feature.
        /// </value>
        [JsonProperty(PropertyName = "databaseApiStatus")]
        [JsonConverter(typeof(Oci.Common.Utils.ResponseEnumConverter))]
        public System.Nullable<DatabaseApiStatusEnum> DatabaseApiStatus { get; set; }
                ///
        /// <value>
        /// The RESTful service definition location.
        /// </value>
        ///
        public enum MetadataSourceEnum {
            [EnumMember(Value = "DATABASE")]
            Database,
            [EnumMember(Value = "CLOUD")]
            Cloud
        };

        /// <value>
        /// The RESTful service definition location.
        /// </value>
        [JsonProperty(PropertyName = "metadataSource")]
        [JsonConverter(typeof(Oci.Common.Utils.ResponseEnumConverter))]
        public System.Nullable<MetadataSourceEnum> MetadataSource { get; set; }
        
        /// <value>
        /// Specifies the HTTP listen port. 0 disables HTTP. Use of ports below 1024 requires elevated (root) privileges and is generally discouraged; deployment on non-privileged ports (1024\u201365535) is recommended.
        /// </value>
        [JsonProperty(PropertyName = "httpPort")]
        public System.Nullable<int> HttpPort { get; set; }
        
        /// <value>
        /// Specifies the HTTPS listen port. 0 disables HTTPS. Use of ports below 1024 requires elevated (root) privileges and is generally discouraged; deployment on non-privileged ports (1024\u201365535) is recommended. ORDS will use a self-signed certificate if a certificate bundle is not provided.
        /// </value>
        [JsonProperty(PropertyName = "httpsPort")]
        public System.Nullable<int> HttpsPort { get; set; }
        
        [JsonProperty(PropertyName = "certificateBundle")]
        public DatabaseApiGatewayConfigCertificateBundle CertificateBundle { get; set; }
        
        /// <value>
        /// The location of the static resources to be served under the / root server path.
        /// </value>
        [JsonProperty(PropertyName = "documentRoot")]
        public string DocumentRoot { get; set; }
        
        /// <value>
        /// Advanced global properties.
        /// </value>
        [JsonProperty(PropertyName = "advancedProperties")]
        public System.Collections.Generic.Dictionary<string, string> AdvancedProperties { get; set; }
        
        /// <value>
        /// The time the resource was created. An RFC3339 formatted datetime string.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "TimeCreated is required.")]
        [JsonProperty(PropertyName = "timeCreated")]
        public System.Nullable<System.DateTime> TimeCreated { get; set; }
        
        /// <value>
        /// The time the resource was updated. An RFC3339 formatted datetime string.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "TimeUpdated is required.")]
        [JsonProperty(PropertyName = "timeUpdated")]
        public System.Nullable<System.DateTime> TimeUpdated { get; set; }
        
    }

    public class DatabaseToolsDatabaseApiGatewayConfigGlobalModelConverter : JsonConverter
    {
        private static NLog.Logger logger = NLog.LogManager.GetCurrentClassLogger();
        public override bool CanWrite => false;
        public override bool CanRead => true;
        public override bool CanConvert(System.Type type)
        {
            return type == typeof(DatabaseToolsDatabaseApiGatewayConfigGlobal);
        }
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            throw new System.InvalidOperationException("Use default serialization.");
        }

        public override object ReadJson(JsonReader reader, System.Type objectType, object existingValue, JsonSerializer serializer)
        {
            var jsonObject = JObject.Load(reader);
            var obj = default(DatabaseToolsDatabaseApiGatewayConfigGlobal);
            var discriminator = jsonObject["type"].Value<string>();
            switch (discriminator)
            {
                case "DEFAULT":
                    obj = new DatabaseToolsDatabaseApiGatewayConfigGlobalDefault();
                    break;
            }
            if (obj != null)
            {
                serializer.Populate(jsonObject.CreateReader(), obj);
            }
            else
            {
                logger.Warn($"The type {discriminator} is not present under DatabaseToolsDatabaseApiGatewayConfigGlobal! Returning null value.");
            }
            return obj;
        }
    }
}
