/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.DatabasetoolsruntimeService.Models
{
    /// <summary>
    /// Metadata of the column
    /// </summary>
    public class ExecuteSqlResponseItemResultSetMetadata 
    {
        
        /// <value>
        /// Name of the column in the Oracle Database.
        /// </value>
        [JsonProperty(PropertyName = "databaseColumnName")]
        public string DatabaseColumnName { get; set; }
        
        /// <value>
        /// Name of the column in the response Result Set.
        /// </value>
        [JsonProperty(PropertyName = "uniqueColumnName")]
        public string UniqueColumnName { get; set; }
        
        /// <value>
        /// Oracle Database data type of the column.
        /// </value>
        [JsonProperty(PropertyName = "columnTypeName")]
        public string ColumnTypeName { get; set; }
        
        /// <value>
        /// Precision of the column.
        /// </value>
        [JsonProperty(PropertyName = "precision")]
        public System.Nullable<int> Precision { get; set; }
        
        /// <value>
        /// Scale of the column.
        /// </value>
        [JsonProperty(PropertyName = "scale")]
        public System.Nullable<int> Scale { get; set; }
        
        /// <value>
        /// Specifies if the column is nullable (0 if the column is not nullable)
        /// </value>
        [JsonProperty(PropertyName = "isNullable")]
        public System.Nullable<bool> IsNullable { get; set; }
        
    }
}
