/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.DatabasetoolsruntimeService.Models
{
    /// <summary>
    /// Contains the details of an APEX property set
    /// </summary>
    public class PropertySetApex : PropertySet
    {
        
        /// <value>
        /// The version of APEX
        /// </value>
        [JsonProperty(PropertyName = "version")]
        public string Version { get; set; }
        
        /// <value>
        /// The APEX engine schema name
        /// </value>
        [JsonProperty(PropertyName = "userKey")]
        public string UserKey { get; set; }
        
        [JsonProperty(PropertyName = "key")]
        private readonly string key = "APEX";
    }
}
