/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.DatabasetoolsruntimeService.Models
{
    /// <summary>
    /// External identity provider for AZURE_AD
    /// </summary>
    public class PropertySetOracleDatabaseExternalAuthenticationIdentityProviderAzureAd : PropertySetOracleDatabaseExternalAuthenticationIdentityProvider
    {
        
        /// <value>
        /// External identity provider configuration parameters. Simple key-value pair
        /// Example: { &quot;tenant_id&quot;: &quot;...&quot;, &quot;application_id_uri&quot;: &quot;...&quot;, ... }
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "Configs is required.")]
        [JsonProperty(PropertyName = "configs")]
        public System.Collections.Generic.Dictionary<string, string> Configs { get; set; }
        
        [JsonProperty(PropertyName = "type")]
        private readonly string type = "AZURE_AD";
    }
}
