/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.DatabasetoolsruntimeService.Models
{
    /// <summary>
    /// Contains the update details of an APEX document generator property set
    /// </summary>
    public class UpdatePropertySetApexDocumentGeneratorDetails : UpdatePropertySetDetails
    {
        
        /// <value>
        /// The print server type
        /// </value>
        [JsonProperty(PropertyName = "printServerType")]
        [JsonConverter(typeof(StringEnumConverter))]
        public System.Nullable<PropertySetApexDocumentGenerator.PrintServerTypeEnum> PrintServerType { get; set; }
        
        /// <value>
        /// The name of the credential used by APEX to manage Object Storage Buckets and Objects as well as invoke the Document Generator function.
        /// </value>
        [JsonProperty(PropertyName = "credentialKey")]
        public string CredentialKey { get; set; }
        
        /// <value>
        /// The status of the Autonomous Database Serverless Resource Principal (OCI$RESOURCE_PRINCIPAL)
        /// </value>
        [JsonProperty(PropertyName = "autonomousDatabaseResourcePrincipalStatus")]
        [JsonConverter(typeof(StringEnumConverter))]
        public System.Nullable<PropertySetApexDocumentGenerator.AutonomousDatabaseResourcePrincipalStatusEnum> AutonomousDatabaseResourcePrincipalStatus { get; set; }
        
        /// <value>
        /// The Object Storage Namespace containing the Object Storage Buckets managed by APEX
        /// </value>
        [JsonProperty(PropertyName = "objectStorageNamespace")]
        public string ObjectStorageNamespace { get; set; }
        
        /// <value>
        /// The [OCID](https://docs.cloud.oracle.com/Content/General/Concepts/identifiers.htm) of the compartment containing the Object Storage Buckets managed by APEX
        /// </value>
        [JsonProperty(PropertyName = "objectStorageBucketCompartmentId")]
        public string ObjectStorageBucketCompartmentId { get; set; }
        
        /// <value>
        /// Object Storage Endpoint
        /// </value>
        [JsonProperty(PropertyName = "objectStorageEndpoint")]
        public string ObjectStorageEndpoint { get; set; }
        
        /// <value>
        /// The [OCID](https://docs.cloud.oracle.com/Content/General/Concepts/identifiers.htm) of the Document Generator function
        /// </value>
        [JsonProperty(PropertyName = "functionId")]
        public string FunctionId { get; set; }
        
        /// <value>
        /// The base endpoint URL to use to invoke the Document Generator function
        /// </value>
        [JsonProperty(PropertyName = "invokeEndpoint")]
        public string InvokeEndpoint { get; set; }
        
        [JsonProperty(PropertyName = "key")]
        private readonly string key = "APEX_DOCUMENT_GENERATOR";
    }
}
