/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.DatabasetoolsruntimeService.Models
{
    /// <summary>
    /// Connection validation result for the Oracle Database.
    /// </summary>
    public class ValidateDatabaseToolsConnectionOracleDatabaseResult : ValidateDatabaseToolsConnectionResult
    {
        
        /// <value>
        /// The database name.
        /// </value>
        [JsonProperty(PropertyName = "databaseName")]
        public string DatabaseName { get; set; }
        
        /// <value>
        /// The database version.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "DatabaseVersion is required.")]
        [JsonProperty(PropertyName = "databaseVersion")]
        public string DatabaseVersion { get; set; }
        
        /// <value>
        /// The name of the currently active default schema.
        /// </value>
        [JsonProperty(PropertyName = "currentSchema")]
        public string CurrentSchema { get; set; }
        
        /// <value>
        /// The name of the session user (the user who logged on).
        /// </value>
        [JsonProperty(PropertyName = "sessionUser")]
        public string SessionUser { get; set; }
        
        /// <value>
        /// Name of the database user who opened the current session on behalf of sessionUser.
        /// </value>
        [JsonProperty(PropertyName = "proxyUser")]
        public string ProxyUser { get; set; }
        
        /// <value>
        /// Returns the identity used in authentication.
        /// </value>
        [JsonProperty(PropertyName = "authenticatedIdentity")]
        public string AuthenticatedIdentity { get; set; }
        
        /// <value>
        /// Returns the method of authentication.
        /// </value>
        [JsonProperty(PropertyName = "authenticationMethod")]
        public string AuthenticationMethod { get; set; }
        
        /// <value>
        /// The DBMS_CLOUD package installation status.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "DbmsCloudStatus is required.")]
        [JsonProperty(PropertyName = "dbmsCloudStatus")]
        [JsonConverter(typeof(Oci.Common.Utils.ResponseEnumConverter))]
        public System.Nullable<DbmsCloudStatus> DbmsCloudStatus { get; set; }
        
        /// <value>
        /// Displays the CLOUD_SERVICE value within the USERENV context
        /// </value>
        [JsonProperty(PropertyName = "cloudService")]
        public string CloudService { get; set; }
        
        /// <value>
        /// Status on whether an identity type can be used with this connection or not.
        /// </value>
        [JsonProperty(PropertyName = "databaseToolsIdentityStatuses")]
        public System.Collections.Generic.List<ValidationIdentityStatus> DatabaseToolsIdentityStatuses { get; set; }
        
        /// <value>
        /// Displays the enterprise identity value within the USERENV context
        /// </value>
        [JsonProperty(PropertyName = "enterpriseIdentity")]
        public string EnterpriseIdentity { get; set; }
        
        /// <value>
        /// Displays the proxy enterprise identity value within the USERENV context
        /// </value>
        [JsonProperty(PropertyName = "proxyEnterpriseIdentity")]
        public string ProxyEnterpriseIdentity { get; set; }
        
        /// <value>
        /// Status on whether an external authentication can be used with this connection or not.
        /// </value>
        [JsonProperty(PropertyName = "externalAuthenticationStatuses")]
        public System.Collections.Generic.List<ValidationExternalAuthenticationStatus> ExternalAuthenticationStatuses { get; set; }
        
        [JsonProperty(PropertyName = "type")]
        private readonly string type = "ORACLE_DATABASE";
    }
}
