/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.AnalyticsService.Models
{
    /// <summary>
    /// Analytics instance private access channel model.
    /// 
    /// </summary>
    public class PrivateAccessChannel 
    {
        
        /// <value>
        /// Private access channel unique identifier key.
        /// 
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "Key is required.")]
        [JsonProperty(PropertyName = "key")]
        public string Key { get; set; }
        
        /// <value>
        /// Display name of the private access channel.
        /// 
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "DisplayName is required.")]
        [JsonProperty(PropertyName = "displayName")]
        public string DisplayName { get; set; }
        
        /// <value>
        /// OCID of the customer VCN peered with the private access channel.
        /// 
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "VcnId is required.")]
        [JsonProperty(PropertyName = "vcnId")]
        public string VcnId { get; set; }
        
        /// <value>
        /// OCID of the customer subnet connected to the private access channel.
        /// 
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "SubnetId is required.")]
        [JsonProperty(PropertyName = "subnetId")]
        public string SubnetId { get; set; }
        
        /// <value>
        /// IP address of the private access channel.
        /// 
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "IpAddress is required.")]
        [JsonProperty(PropertyName = "ipAddress")]
        public string IpAddress { get; set; }
        
        /// <value>
        /// List of IP addresses from the customer subnet connected to the private access channel, used as a source IP by the private access channel
        /// for network traffic from the Analytics instance to the private sources.
        /// 
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "EgressSourceIpAddresses is required.")]
        [JsonProperty(PropertyName = "egressSourceIpAddresses")]
        public System.Collections.Generic.List<string> EgressSourceIpAddresses { get; set; }
        
        /// <value>
        /// List of private source DNS zones registered with the private access channel. The
        ///  datasource hostnames from these DNS zones / domains will be resolved in the peered VCN for access from  the Analytics instance.
        /// Minimum 1 private source is required. Maximum 30 private source DNS zones can be registered.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "privateSourceDnsZones")]
        public System.Collections.Generic.List<PrivateSourceDnsZone> PrivateSourceDnsZones { get; set; }
        
        /// <value>
        /// List of private source database SCAN hosts registered with the private access channel for access from the Analytics instance.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "privateSourceScanHosts")]
        public System.Collections.Generic.List<PrivateSourceScanHost> PrivateSourceScanHosts { get; set; }
        
        /// <value>
        /// Network Security Group OCIDs for the Analytics instance.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "networkSecurityGroupIds")]
        public System.Collections.Generic.List<string> NetworkSecurityGroupIds { get; set; }
        
    }
}
