/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.LoganalyticsService.Models
{
    /// <summary>
    /// This is the namespace details of a tenancy in Log Analytics application
    /// </summary>
    public class Namespace 
    {
        
        /// <value>
        /// This is the namespace name of a tenancy
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "NamespaceName is required.")]
        [JsonProperty(PropertyName = "namespaceName")]
        public string NamespaceName { get; set; }
        
        /// <value>
        /// The is the tenancy ID
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "CompartmentId is required.")]
        [JsonProperty(PropertyName = "compartmentId")]
        public string CompartmentId { get; set; }
        
        /// <value>
        /// This indicates if the tenancy is onboarded to Log Analytics
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "IsOnboarded is required.")]
        [JsonProperty(PropertyName = "isOnboarded")]
        public System.Nullable<bool> IsOnboarded { get; set; }
        
        /// <value>
        /// This indicates if the log set feature is enabled for the tenancy
        /// </value>
        [JsonProperty(PropertyName = "isLogSetEnabled")]
        public System.Nullable<bool> IsLogSetEnabled { get; set; }
        
        /// <value>
        /// This indicates if data has ever been ingested for the tenancy in Log Analytics
        /// </value>
        [JsonProperty(PropertyName = "isDataEverIngested")]
        public System.Nullable<bool> IsDataEverIngested { get; set; }
        
        /// <value>
        /// This indicates if old data can be archived for a tenancy
        /// </value>
        [JsonProperty(PropertyName = "isArchivingEnabled")]
        public System.Nullable<bool> IsArchivingEnabled { get; set; }
                ///
        /// <value>
        /// The current state of the compartment.
        /// </value>
        ///
        public enum LifecycleStateEnum {
            /// This value is used if a service returns a value for this enum that is not recognized by this version of the SDK.
            [EnumMember(Value = null)]
            UnknownEnumValue,
            [EnumMember(Value = "ACTIVE")]
            Active,
            [EnumMember(Value = "INACTIVE")]
            Inactive
        };

        /// <value>
        /// The current state of the compartment.
        /// </value>
        [JsonProperty(PropertyName = "lifecycleState")]
        [JsonConverter(typeof(Oci.Common.Utils.ResponseEnumConverter))]
        public System.Nullable<LifecycleStateEnum> LifecycleState { get; set; }
        
    }
}
