/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.FunctionsService.Models
{
    /// <summary>
    /// Source details for creating the archive based function from Direct Archive. 
    /// This allows the API caller to directly upload the function code as a base64-encoded archive file. 
    /// It is useful when the caller wants to provide the code inline during function creation.
    /// 
    /// </summary>
    public class CreateDirectArchiveSourceDetails : CreateArchiveSourceDetails
    {
        
        /// <value>
        /// The base64-encoded archive file of the function code. The archive file must contain all the files for the function. Please refer to functions documentation for maximum allowed size and supported archive formats.
        /// 
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "ArchiveFile is required.")]
        [JsonProperty(PropertyName = "archiveFile")]
        public System.Byte[] ArchiveFile { get; set; }
        
        [JsonProperty(PropertyName = "archiveSourceType")]
        private readonly string archiveSourceType = "DIRECT_ARCHIVE";
    }
}
