/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace Oci.FunctionsService.Models
{
    /// <summary>
    /// The source details for creating the Function. The function can be created from various sources.
    /// 
    /// </summary>
    [JsonConverter(typeof(CreateFunctionSourceDetailsModelConverter))]
    public class CreateFunctionSourceDetails 
    {
                ///
        /// <value>
        /// Type of the Function Source. Possible values: CONTAINER_IMAGE, PBF and ARCHIVE.
        /// 
        /// </value>
        ///
        public enum SourceTypeEnum {
            [EnumMember(Value = "PRE_BUILT_FUNCTIONS")]
            PreBuiltFunctions,
            [EnumMember(Value = "ARCHIVE")]
            Archive,
            [EnumMember(Value = "CONTAINER_IMAGE")]
            ContainerImage
        };

        
    }

    public class CreateFunctionSourceDetailsModelConverter : JsonConverter
    {
        public override bool CanWrite => false;
        public override bool CanRead => true;
        public override bool CanConvert(System.Type type)
        {
            return type == typeof(CreateFunctionSourceDetails);
        }
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            throw new System.InvalidOperationException("Use default serialization.");
        }

        public override object ReadJson(JsonReader reader, System.Type objectType, object existingValue, JsonSerializer serializer)
        {
            var jsonObject = JObject.Load(reader);
            var obj = default(CreateFunctionSourceDetails);
            var discriminator = jsonObject["sourceType"].Value<string>();
            switch (discriminator)
            {
                case "PRE_BUILT_FUNCTIONS":
                    obj = new CreatePreBuiltFunctionSourceDetails();
                    break;
                case "ARCHIVE":
                    obj = new CreateArchiveFunctionSourceDetails();
                    break;
                case "CONTAINER_IMAGE":
                    obj = new CreateContainerImageFunctionSourceDetails();
                    break;
            }
            serializer.Populate(jsonObject.CreateReader(), obj);
            return obj;
        }
    }
}
