/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.FunctionsService.Models
{
    /// <summary>
    /// FunctionsRuntime configuration for a function with 'FUNCTION_UPDATE' Runtime Update strategy.
    /// 
    /// </summary>
    public class FunctionUpdateRuntimeConfig : RuntimeConfig
    {
        
        /// <value>
        /// The name of the FunctionsRuntime this function is to be associated with.
        /// 
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "FunctionsRuntimeName is required.")]
        [JsonProperty(PropertyName = "functionsRuntimeName")]
        public string FunctionsRuntimeName { get; set; }
        
        /// <value>
        /// The OCID of the FunctionsRuntimeVersion that is currently in use for the function.
        /// </value>
        [JsonProperty(PropertyName = "functionsRuntimeVersionId")]
        public string FunctionsRuntimeVersionId { get; set; }
        
        [JsonProperty(PropertyName = "runtimeConfigType")]
        private readonly string runtimeConfigType = "FUNCTION_UPDATE";
    }
}
