/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace Oci.FunctionsService.Models
{
    /// <summary>
    /// FunctionsRuntime configuration used to update a function.
    /// 
    /// </summary>
    [JsonConverter(typeof(UpdateRuntimeConfigModelConverter))]
    public class UpdateRuntimeConfig 
    {
                ///
        /// <value>
        /// Type of the FunctionsRuntime Config. Possible values: FUNCTION_UPDATE and MANUAL.
        /// 
        /// </value>
        ///
        public enum RuntimeConfigTypeEnum {
            [EnumMember(Value = "FUNCTION_UPDATE")]
            FunctionUpdate,
            [EnumMember(Value = "MANUAL")]
            Manual
        };

        
    }

    public class UpdateRuntimeConfigModelConverter : JsonConverter
    {
        public override bool CanWrite => false;
        public override bool CanRead => true;
        public override bool CanConvert(System.Type type)
        {
            return type == typeof(UpdateRuntimeConfig);
        }
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            throw new System.InvalidOperationException("Use default serialization.");
        }

        public override object ReadJson(JsonReader reader, System.Type objectType, object existingValue, JsonSerializer serializer)
        {
            var jsonObject = JObject.Load(reader);
            var obj = default(UpdateRuntimeConfig);
            var discriminator = jsonObject["runtimeConfigType"].Value<string>();
            switch (discriminator)
            {
                case "MANUAL":
                    obj = new UpdateManualRuntimeConfig();
                    break;
                case "FUNCTION_UPDATE":
                    obj = new UpdateFunctionUpdateRuntimeConfig();
                    break;
            }
            serializer.Populate(jsonObject.CreateReader(), obj);
            return obj;
        }
    }
}
