/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace Oci.FunctionsService.Models
{
    /// <summary>
    /// Source details for updating an archive\u2011based function.
    /// 
    /// </summary>
    [JsonConverter(typeof(UpdateArchiveSourceDetailsModelConverter))]
    public class UpdateArchiveSourceDetails 
    {
                ///
        /// <value>
        /// Type of the Archive Source. Possible values: OBJECT_STORAGE_ARCHIVE and DIRECT_ARCHIVE.
        /// 
        /// </value>
        ///
        public enum ArchiveSourceTypeEnum {
            [EnumMember(Value = "OBJECT_STORAGE_ARCHIVE")]
            ObjectStorageArchive,
            [EnumMember(Value = "DIRECT_ARCHIVE")]
            DirectArchive
        };

        
    }

    public class UpdateArchiveSourceDetailsModelConverter : JsonConverter
    {
        public override bool CanWrite => false;
        public override bool CanRead => true;
        public override bool CanConvert(System.Type type)
        {
            return type == typeof(UpdateArchiveSourceDetails);
        }
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            throw new System.InvalidOperationException("Use default serialization.");
        }

        public override object ReadJson(JsonReader reader, System.Type objectType, object existingValue, JsonSerializer serializer)
        {
            var jsonObject = JObject.Load(reader);
            var obj = default(UpdateArchiveSourceDetails);
            var discriminator = jsonObject["archiveSourceType"].Value<string>();
            switch (discriminator)
            {
                case "DIRECT_ARCHIVE":
                    obj = new UpdateDirectArchiveSourceDetails();
                    break;
                case "OBJECT_STORAGE_ARCHIVE":
                    obj = new UpdateObjectStorageArchiveSourceDetails();
                    break;
            }
            serializer.Populate(jsonObject.CreateReader(), obj);
            return obj;
        }
    }
}
