/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.IdentitydomainsService.Models
{
    /// <summary>
    /// Certificate trust store. This is required if identity propagation type is X509.
    /// <br/>
    /// **Added In:** 2508041610
    /// <br/>
    /// **SCIM++ Properties:**
    ///  - caseExact: true
    ///  - type: complex
    ///  - multiValued: false
    ///  - required: false
    ///  - mutability: readWrite
    ///  - returned: default
    ///  - uniqueness: none
    /// </summary>
    public class IdentityPropagationTrustCaCertChain 
    {
        
        /// <value>
        /// A list of PEM-encoded root CA certificates.
        /// <br/>
        /// **Added In:** 2508041610
        /// <br/>
        /// **SCIM++ Properties:**
        ///  - caseExact: true
        ///  - type: string
        ///  - multiValued: true
        ///  - required: true
        ///  - mutability: readWrite
        ///  - returned: default
        ///  - uniqueness: none
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "RootCAs is required.")]
        [JsonProperty(PropertyName = "rootCAs")]
        public System.Collections.Generic.List<string> RootCAs { get; set; }
        
        /// <value>
        /// A list of PEM-encoded intermediate CA certificates.
        /// <br/>
        /// **Added In:** 2508041610
        /// <br/>
        /// **SCIM++ Properties:**
        ///  - caseExact: true
        ///  - type: string
        ///  - multiValued: true
        ///  - required: false
        ///  - mutability: readWrite
        ///  - returned: default
        ///  - uniqueness: none
        /// </value>
        [JsonProperty(PropertyName = "intermediateCAs")]
        public System.Collections.Generic.List<string> IntermediateCAs { get; set; }
        
    }
}
