/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.PsqlService.Models
{
    /// <summary>
    /// Describes supported insight types and their capabilities.
    /// </summary>
    public class InsightCapabilitySummary 
    {
                ///
        /// <value>
        /// Echo of the requested insight type.
        /// </value>
        ///
        public enum InsightTypeEnum {
            /// This value is used if a service returns a value for this enum that is not recognized by this version of the SDK.
            [EnumMember(Value = null)]
            UnknownEnumValue,
            [EnumMember(Value = "QUERY_INSIGHT")]
            QueryInsight
        };

        /// <value>
        /// Echo of the requested insight type.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "InsightType is required.")]
        [JsonProperty(PropertyName = "insightType")]
        [JsonConverter(typeof(Oci.Common.Utils.ResponseEnumConverter))]
        public System.Nullable<InsightTypeEnum> InsightType { get; set; }
        
        /// <value>
        /// Human-readable description of the insight type.
        /// </value>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }
        
        /// <value>
        /// Supported insight data types for this insight type.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "DataTypeCapabilities is required.")]
        [JsonProperty(PropertyName = "dataTypeCapabilities")]
        public System.Collections.Generic.List<InsightDataTypeCapability> DataTypeCapabilities { get; set; }
        
    }
}
