/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.PsqlService.Models
{
    /// <summary>
    /// Details of database system point-in-time recovery.
    /// 
    /// </summary>
    public class PointInTimeDbSystemSourceDetails : SourceDetails
    {
        
        /// <value>
        /// The [OCID](https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the source database system which will be used to perform point-in-time recovery.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "DbSystemId is required.")]
        [JsonProperty(PropertyName = "dbSystemId")]
        public string DbSystemId { get; set; }
        
        /// <value>
        /// The target point-in-time of the source database system that will be restored, expressed in
        /// [RFC 3339](https://tools.ietf.org/rfc/rfc3339) timestamp format.
        /// <br/>
        /// Point-in-time recovery can only performed in granularity of seconds.
        /// Example: 2016-08-25T21:10:29Z
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "TimeToRestore is required.")]
        [JsonProperty(PropertyName = "timeToRestore")]
        public System.Nullable<System.DateTime> TimeToRestore { get; set; }
        
        [JsonProperty(PropertyName = "sourceType")]
        private readonly string sourceType = "POINT_IN_TIME_DB_SYSTEM";
    }
}
