/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.DatasafeService.Models
{
    /// <summary>
    /// Wallet details for one crypto feature.
    /// </summary>
    public class CryptoAssessmentWalletSummary 
    {
        
        /// <value>
        /// OCID of the crypto assessment that discovered the wallet.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "AssessmentId is required.")]
        [JsonProperty(PropertyName = "assessmentId")]
        public string AssessmentId { get; set; }
        
        /// <value>
        /// The date and time the associated crypto assessment was last assessed, in RFC3339 format.
        /// </value>
        [JsonProperty(PropertyName = "timeLastAssessed")]
        public System.Nullable<System.DateTime> TimeLastAssessed { get; set; }
        
        /// <value>
        /// OCID of the target database associated with the wallet.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "TargetId is required.")]
        [JsonProperty(PropertyName = "targetId")]
        public string TargetId { get; set; }
                ///
        /// <value>
        /// Crypto feature for which wallet details are reported.
        /// </value>
        ///
        public enum FeatureEnum {
            /// This value is used if a service returns a value for this enum that is not recognized by this version of the SDK.
            [EnumMember(Value = null)]
            UnknownEnumValue,
            [EnumMember(Value = "TDE")]
            Tde,
            [EnumMember(Value = "TLS")]
            Tls,
            [EnumMember(Value = "NNE")]
            Nne,
            [EnumMember(Value = "ZDLRA")]
            Zdlra
        };

        /// <value>
        /// Crypto feature for which wallet details are reported.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "Feature is required.")]
        [JsonProperty(PropertyName = "feature")]
        [JsonConverter(typeof(Oci.Common.Utils.ResponseEnumConverter))]
        public System.Nullable<FeatureEnum> Feature { get; set; }
        
        /// <value>
        /// Wallet path for the feature.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "WalletLocation is required.")]
        [JsonProperty(PropertyName = "walletLocation")]
        public string WalletLocation { get; set; }
                ///
        /// <value>
        /// Whether wallet auto-login is enabled.
        /// </value>
        ///
        public enum AutoLoginEnum {
            /// This value is used if a service returns a value for this enum that is not recognized by this version of the SDK.
            [EnumMember(Value = null)]
            UnknownEnumValue,
            [EnumMember(Value = "ENABLED")]
            Enabled,
            [EnumMember(Value = "DISABLED")]
            Disabled,
            [EnumMember(Value = "NOT_APPLICABLE")]
            NotApplicable,
            [EnumMember(Value = "NOT_SUPPORTED")]
            NotSupported
        };

        /// <value>
        /// Whether wallet auto-login is enabled.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "AutoLogin is required.")]
        [JsonProperty(PropertyName = "autoLogin")]
        [JsonConverter(typeof(Oci.Common.Utils.ResponseEnumConverter))]
        public System.Nullable<AutoLoginEnum> AutoLogin { get; set; }
        
        /// <value>
        /// Wallet creation time in RFC3339 format.
        /// </value>
        [JsonProperty(PropertyName = "timeCreated")]
        public System.Nullable<System.DateTime> TimeCreated { get; set; }
        
        /// <value>
        /// Wallet encryption algorithm.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "WalletEncryptionAlgorithm is required.")]
        [JsonProperty(PropertyName = "walletEncryptionAlgorithm")]
        public string WalletEncryptionAlgorithm { get; set; }
        
    }
}
