/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.DatasafeService.Models
{
    /// <summary>
    /// List of crypto deviation findings for the specified crypto assessment.
    /// </summary>
    public class CryptoAssessmentFindingCollection 
    {
        
        /// <value>
        /// The OCID of the target database for the specified crypto assessment.
        /// </value>
        [JsonProperty(PropertyName = "targetId")]
        public string TargetId { get; set; }
        
        /// <value>
        /// Assessment type recorded in the findings table.
        /// </value>
        [JsonProperty(PropertyName = "assessmentType")]
        [JsonConverter(typeof(StringEnumConverter))]
        public System.Nullable<CryptoAssessment.TypeEnum> AssessmentType { get; set; }
        
        /// <value>
        /// Database version for the target database associated with the specified crypto assessment.
        /// </value>
        [JsonProperty(PropertyName = "databaseVersion")]
        public string DatabaseVersion { get; set; }
        
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "Summary is required.")]
        [JsonProperty(PropertyName = "summary")]
        public CryptoAssessmentFindingSummaryMetrics Summary { get; set; }
        
        /// <value>
        /// Array of crypto deviation findings.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "Items is required.")]
        [JsonProperty(PropertyName = "items")]
        public System.Collections.Generic.List<CryptoAssessmentFindingSummary> Items { get; set; }
        
    }
}
