/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.DatasafeService.Models
{
    /// <summary>
    /// One crypto deviation finding for a specific assessment run.
    /// </summary>
    public class CryptoAssessmentFindingSummary 
    {
        
        /// <value>
        /// Unique key identifier for the finding.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "FindingKey is required.")]
        [JsonProperty(PropertyName = "findingKey")]
        public string FindingKey { get; set; }
        
        /// <value>
        /// Human-readable title for the finding.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "Title is required.")]
        [JsonProperty(PropertyName = "title")]
        public string Title { get; set; }
        
        /// <value>
        /// Category value recorded for the finding.
        /// </value>
        [JsonProperty(PropertyName = "category")]
        public string Category { get; set; }
        
        /// <value>
        /// Numeric priority of the finding. 1 is CRITICAL, 2 is HIGH, 3 is MEDIUM, and 4 is LOW.
        /// </value>
        [JsonProperty(PropertyName = "priority")]
        public System.Nullable<int> Priority { get; set; }
                ///
        /// <value>
        /// Text severity derived from priority using the static mapping 1=CRITICAL, 2=HIGH, 3=MEDIUM, 4=LOW.
        /// </value>
        ///
        public enum SeverityEnum {
            /// This value is used if a service returns a value for this enum that is not recognized by this version of the SDK.
            [EnumMember(Value = null)]
            UnknownEnumValue,
            [EnumMember(Value = "CRITICAL")]
            Critical,
            [EnumMember(Value = "HIGH")]
            High,
            [EnumMember(Value = "MEDIUM")]
            Medium,
            [EnumMember(Value = "LOW")]
            Low
        };

        /// <value>
        /// Text severity derived from priority using the static mapping 1=CRITICAL, 2=HIGH, 3=MEDIUM, 4=LOW.
        /// </value>
        [JsonProperty(PropertyName = "severity")]
        [JsonConverter(typeof(Oci.Common.Utils.ResponseEnumConverter))]
        public System.Nullable<SeverityEnum> Severity { get; set; }
        
        /// <value>
        /// Expected value recorded for the finding.
        /// </value>
        [JsonProperty(PropertyName = "expectedValue")]
        public string ExpectedValue { get; set; }
        
        /// <value>
        /// Observed values recorded for the finding.
        /// </value>
        [JsonProperty(PropertyName = "observedValue")]
        public System.Collections.Generic.List<string> ObservedValue { get; set; }
        
        /// <value>
        /// Recommended value recorded for the finding.
        /// </value>
        [JsonProperty(PropertyName = "recommendedValue")]
        public string RecommendedValue { get; set; }
        
        /// <value>
        /// Status recorded for the finding.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "Status is required.")]
        [JsonProperty(PropertyName = "status")]
        [JsonConverter(typeof(Oci.Common.Utils.ResponseEnumConverter))]
        public System.Nullable<CryptoFindingStatus> Status { get; set; }
        
        /// <value>
        /// Indicates whether this finding is part of quantum-readiness checks.
        /// </value>
        [JsonProperty(PropertyName = "isQuantumReadinessCheck")]
        public System.Nullable<bool> IsQuantumReadinessCheck { get; set; }
        
        /// <value>
        /// Summary recorded for the finding.
        /// </value>
        [JsonProperty(PropertyName = "summary")]
        public string Summary { get; set; }
        
        /// <value>
        /// Short summary of the finding.
        /// </value>
        [JsonProperty(PropertyName = "shortSummary")]
        public string ShortSummary { get; set; }
        
        /// <value>
        /// URL recorded for the finding.
        /// </value>
        [JsonProperty(PropertyName = "url")]
        public string Url { get; set; }
        
        /// <value>
        /// Remediation text recorded for the finding.
        /// </value>
        [JsonProperty(PropertyName = "remediation")]
        public string Remediation { get; set; }
        
        /// <value>
        /// Short remediation for the finding.
        /// </value>
        [JsonProperty(PropertyName = "shortRemediation")]
        public string ShortRemediation { get; set; }
        
        /// <value>
        /// Compliance mapping recorded for the finding.
        /// </value>
        [JsonProperty(PropertyName = "compliance")]
        public string Compliance { get; set; }
        
    }
}
