/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;

namespace Oci.DatasafeService.Models
{
  /// <summary>
  /// Category key for crypto findings. These are stable values meant for programmatic use; clients can map them to user-facing labels.
  /// </summary>
  public enum CryptoFindingCategory {
      [EnumMember(Value = "NETWORK_ENCRYPTION")]
      NetworkEncryption,
      [EnumMember(Value = "DATA_ENCRYPTION")]
      DataEncryption,
      [EnumMember(Value = "CERTIFICATES_AND_KEY_MANAGEMENT")]
      CertificatesAndKeyManagement,
      [EnumMember(Value = "BACKUP_AND_EXPORT_ENCRYPTION")]
      BackupAndExportEncryption,
      [EnumMember(Value = "POST_QUANTUM_READINESS")]
      PostQuantumReadiness,
      [EnumMember(Value = "NOT_SUPPORTED")]
      NotSupported
  }
}
