/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.DatasafeService.Models
{
    /// <summary>
    /// Aggregate finding counts for one crypto finding category.
    /// </summary>
    public class CryptoAssessmentFindingCategorySummary 
    {
        
        /// <value>
        /// Findings with PASS status.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "PassChecks is required.")]
        [JsonProperty(PropertyName = "passChecks")]
        public System.Nullable<int> PassChecks { get; set; }
        
        /// <value>
        /// Findings with FAIL or EVALUATE status.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "Findings is required.")]
        [JsonProperty(PropertyName = "findings")]
        public System.Nullable<int> Findings { get; set; }
        
        /// <value>
        /// Total findings across all statuses in this category.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "TotalChecks is required.")]
        [JsonProperty(PropertyName = "totalChecks")]
        public System.Nullable<int> TotalChecks { get; set; }
        
    }
}
