/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.CoreService.Models
{
    /// <summary>
    /// Details for creating an instance configuration for GPU Memory Cluster.
    /// 
    /// </summary>
    public class CreateGmcConfigurationDetails : CreateInstanceConfigurationBase
    {
        
        /// <value>
        /// The GPU Memory Cluster configuration entries for.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "GmcConfigs is required.")]
        [JsonProperty(PropertyName = "gmcConfigs")]
        public System.Collections.Generic.List<InstanceConfigurationGmcConfigDetail> GmcConfigs { get; set; }
        
        [JsonProperty(PropertyName = "source")]
        private readonly string source = "GMC";
    }
}
