/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.CoreService.Models
{
    /// <summary>
    /// The request to patch the VCN.
    /// Example:       {        &quot;patchVcnInstructions&quot;: [          {            &quot;operation&quot;: &quot;REPLACE&quot;,            &quot;selection&quot;: &quot;ipv6CidrBlock&quot;,            &quot;value&quot;: {&quot;cidr&quot;: &quot;2001::/56&quot;}          },          {            &quot;operation&quot;: &quot;REPLACE&quot;,            &quot;selection&quot;: &quot;ipv6PublicCidrBlock&quot;,            &quot;value&quot;: {&quot;cidr&quot;: &quot;2001:0db8:0123::/48&quot;}          },          {            &quot;operation&quot;: &quot;REPLACE&quot;,            &quot;selection&quot;: &quot;byoipv6CidrDetails&quot;,            &quot;value&quot;: {              &quot;cidrs&quot;: [                {                  &quot;byoipv6RangeId&quot;: &quot;ocid1.byoiprange.oc1.<unique_ID_1>&quot;,                  &quot;ipv6CidrBlock&quot;: &quot;2001:0db8:0123::/48&quot;                },                {                  &quot;byoipv6RangeId&quot;: &quot;ocid1.byoiprange.oc1.<unique_ID_2>&quot;,                  &quot;ipv6CidrBlock&quot;: &quot;2001:0db8:0456::/48&quot;                }              ]            }          },          {            &quot;operation&quot;: &quot;REPLACE&quot;,            &quot;selection&quot;: &quot;ipv6PrivateCidrBlocks&quot;,            &quot;value&quot;: { &quot;cidrs&quot;: [&quot;fd00:1000:0:1::/64&quot;, &quot;fd00:1000:0:2::/64&quot;] }           }        ]      }
    /// </summary>
    public class PatchVcnDetails 
    {
        
        /// <value>
        /// List of patch instructions for VCN.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "PatchVcnInstructions is required.")]
        [JsonProperty(PropertyName = "patchVcnInstructions")]
        public System.Collections.Generic.List<PatchVcnInstruction> PatchVcnInstructions { get; set; }
        
    }
}
