/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.DatabaseService.Models
{
    /// <summary>
    /// Details about the most recent live image version applied on the VM Cluster, if any. If a full OS update was applied, the fields would be blank.
    /// 
    /// </summary>
    public class ExadataLiveImageVersionDetails 
    {
                ///
        /// <value>
        /// The OS live update mode performed most recently on the VM Cluster.
        /// </value>
        ///
        public enum UpdateModeEnum {
            /// This value is used if a service returns a value for this enum that is not recognized by this version of the SDK.
            [EnumMember(Value = null)]
            UnknownEnumValue,
            [EnumMember(Value = "ONLINE_HIGHCVSS")]
            OnlineHighcvss,
            [EnumMember(Value = "ONLINE_ALLCVSS")]
            OnlineAllcvss,
            [EnumMember(Value = "ONLINE_ALL_UPDATES")]
            OnlineAllUpdates
        };

        /// <value>
        /// The OS live update mode performed most recently on the VM Cluster.
        /// </value>
        [JsonProperty(PropertyName = "updateMode")]
        [JsonConverter(typeof(Oci.Common.Utils.ResponseEnumConverter))]
        public System.Nullable<UpdateModeEnum> UpdateMode { get; set; }
        
        /// <value>
        /// Live Exadata Image Version of the Guest OS Update applied.
        /// </value>
        [JsonProperty(PropertyName = "version")]
        public string Version { get; set; }
        
        /// <value>
        /// Indicates whether OS updates that require node reboot are pending after the previous online update was applied.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "hasPendingUpdates")]
        public System.Nullable<bool> HasPendingUpdates { get; set; }
        
        /// <value>
        /// The release date and time for the applied Live Exadata Image OS version.
        /// </value>
        [JsonProperty(PropertyName = "timeReleased")]
        public System.Nullable<System.DateTime> TimeReleased { get; set; }
        
    }
}
