/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.DatabaseService.Models
{
    /// <summary>
    /// Oracle Managed Database Software Updates schedule will be created based on the provided update preferences
    /// 
    /// </summary>
    public class ManagedSoftwareUpdatePreferenceDetails 
    {
        
        /// <value>
        /// The update should be applied on the database for the selected days of the week.
        /// 
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "DaysOfWeek is required.")]
        [JsonProperty(PropertyName = "daysOfWeek")]
        public System.Collections.Generic.List<ManagedSoftwareUpdateDayOfWeek> DaysOfWeek { get; set; }
        
        /// <value>
        /// The update should be applied on the database for the selected hour of the day.
        /// 
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "HourOfDay is required.")]
        [JsonProperty(PropertyName = "hourOfDay")]
        public System.Nullable<int> HourOfDay { get; set; }
                ///
        /// <value>
        /// Oracle Managed Database Software update method, either \"ROLLING\" or \"NONROLLING\". Default value is ROLLING.
        /// *IMPORTANT*: Non-rolling Database Software update update involves system down time.
        /// 
        /// </value>
        ///
        public enum UpdateModeEnum {
            /// This value is used if a service returns a value for this enum that is not recognized by this version of the SDK.
            [EnumMember(Value = null)]
            UnknownEnumValue,
            [EnumMember(Value = "ROLLING")]
            Rolling,
            [EnumMember(Value = "NONROLLING")]
            Nonrolling
        };

        /// <value>
        /// Oracle Managed Database Software update method, either \"ROLLING\" or \"NONROLLING\". Default value is ROLLING.
        /// *IMPORTANT*: Non-rolling Database Software update update involves system down time.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "updateMode")]
        [JsonConverter(typeof(Oci.Common.Utils.ResponseEnumConverter))]
        public System.Nullable<UpdateModeEnum> UpdateMode { get; set; }
        
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "VersionSchemeDetails is required.")]
        [JsonProperty(PropertyName = "versionSchemeDetails")]
        public VersionSchemeDetails VersionSchemeDetails { get; set; }
        
    }
}
