/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.DatabaseService.Models
{
    /// <summary>
    /// Provides details about actual Oracle Managed Database Software Updates scheduled time and version.
    /// 
    /// </summary>
    public class ManagedSoftwareUpdateMaintenanceDetails 
    {
        
        /// <value>
        /// The date and time of the database was scheduled for update.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "TimeScheduled is required.")]
        [JsonProperty(PropertyName = "timeScheduled")]
        public System.Nullable<System.DateTime> TimeScheduled { get; set; }
                ///
        /// <value>
        /// The managed software update readiness status
        /// </value>
        ///
        public enum UpdateReadinessStatusEnum {
            /// This value is used if a service returns a value for this enum that is not recognized by this version of the SDK.
            [EnumMember(Value = null)]
            UnknownEnumValue,
            [EnumMember(Value = "SCHEDULED")]
            Scheduled,
            [EnumMember(Value = "SUCCEEDED")]
            Succeeded,
            [EnumMember(Value = "READY_FOR_MANAGED_UPDATE")]
            ReadyForManagedUpdate,
            [EnumMember(Value = "NOT_READY_FOR_MANAGED_UPDATE")]
            NotReadyForManagedUpdate,
            [EnumMember(Value = "IN_PROGRESS")]
            InProgress,
            [EnumMember(Value = "NEEDS_ATTENTION")]
            NeedsAttention,
            [EnumMember(Value = "AWAITING_RESOLUTION")]
            AwaitingResolution
        };

        /// <value>
        /// The managed software update readiness status
        /// </value>
        [JsonProperty(PropertyName = "updateReadinessStatus")]
        [JsonConverter(typeof(Oci.Common.Utils.ResponseEnumConverter))]
        public System.Nullable<UpdateReadinessStatusEnum> UpdateReadinessStatus { get; set; }
        
        /// <value>
        /// This field will contain actual cause of update readiness state.
        /// </value>
        [JsonProperty(PropertyName = "updateReadinessStatusDetails")]
        public string UpdateReadinessStatusDetails { get; set; }
        
        /// <value>
        /// The date and time of when the status was updated.
        /// </value>
        [JsonProperty(PropertyName = "timeOfStatusUpdate")]
        public System.Nullable<System.DateTime> TimeOfStatusUpdate { get; set; }
                ///
        /// <value>
        /// Oracle Managed Database Software update method, either \"ROLLING\" or \"NONROLLING\"
        /// 
        /// </value>
        ///
        public enum UpdateModeEnum {
            /// This value is used if a service returns a value for this enum that is not recognized by this version of the SDK.
            [EnumMember(Value = null)]
            UnknownEnumValue,
            [EnumMember(Value = "ROLLING")]
            Rolling,
            [EnumMember(Value = "NONROLLING")]
            Nonrolling
        };

        /// <value>
        /// Oracle Managed Database Software update method, either \"ROLLING\" or \"NONROLLING\"
        /// 
        /// </value>
        [JsonProperty(PropertyName = "updateMode")]
        [JsonConverter(typeof(Oci.Common.Utils.ResponseEnumConverter))]
        public System.Nullable<UpdateModeEnum> UpdateMode { get; set; }
        
        /// <value>
        /// The version of the database was scheduled for update.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "Version is required.")]
        [JsonProperty(PropertyName = "version")]
        public string Version { get; set; }
        
        /// <value>
        /// The date and time of the last readiness check.
        /// </value>
        [JsonProperty(PropertyName = "timeOfLastReadinessCheck")]
        public System.Nullable<System.DateTime> TimeOfLastReadinessCheck { get; set; }
        
    }
}
