/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.DatabaseService.Models
{
    /// <summary>
    /// Details to update a database.
    /// <br/>
    /// **Warning:** Oracle recommends that you avoid using any confidential information when you supply string values using the API.
    /// 
    /// </summary>
    public class UpdateDatabaseDetails 
    {
        
        [JsonProperty(PropertyName = "dbBackupConfig")]
        public DbBackupConfig DbBackupConfig { get; set; }
        
        /// <value>
        /// The [OCID](https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the Database Home.
        /// </value>
        [JsonProperty(PropertyName = "dbHomeId")]
        public string DbHomeId { get; set; }
        
        /// <value>
        /// A new strong password for SYS, SYSTEM, and the plugbable database ADMIN user. The password must be at least nine characters and contain at least two uppercase, two lowercase, two numeric, and two special characters. The special characters must be _, \\#, or -.
        /// </value>
        [JsonProperty(PropertyName = "newAdminPassword")]
        public string NewAdminPassword { get; set; }
        
        /// <value>
        /// The existing TDE wallet password. You must provide the existing password in order to set a new TDE wallet password.
        /// </value>
        [JsonProperty(PropertyName = "oldTdeWalletPassword")]
        public string OldTdeWalletPassword { get; set; }
        
        /// <value>
        /// The new password to open the TDE wallet. The password must be at least nine characters and contain at least two uppercase, two lowercase, two numeric, and two special characters. The special characters must be _, \\#, or -.
        /// </value>
        [JsonProperty(PropertyName = "newTdeWalletPassword")]
        public string NewTdeWalletPassword { get; set; }
        
        [JsonProperty(PropertyName = "storageSizeDetails")]
        public DatabaseStorageSizeDetails StorageSizeDetails { get; set; }
        
        /// <value>
        /// Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace.
        /// For more information, see [Resource Tags](https://docs.oracle.com/iaas/Content/General/Concepts/resourcetags.htm).
        /// <br/>
        /// Example: {&quot;Department&quot;: &quot;Finance&quot;}
        /// </value>
        [JsonProperty(PropertyName = "freeformTags")]
        public System.Collections.Generic.Dictionary<string, string> FreeformTags { get; set; }
        
        /// <value>
        /// Defined tags for this resource. Each key is predefined and scoped to a namespace.
        /// For more information, see [Resource Tags](https://docs.oracle.com/iaas/Content/General/Concepts/resourcetags.htm).
        /// 
        /// </value>
        [JsonProperty(PropertyName = "definedTags")]
        public System.Collections.Generic.Dictionary<string, System.Collections.Generic.Dictionary<string, System.Object>> DefinedTags { get; set; }
        
        [JsonProperty(PropertyName = "managedSoftwareUpdateDetails")]
        public ManagedSoftwareUpdateInputDetails ManagedSoftwareUpdateDetails { get; set; }
        
        [JsonProperty(PropertyName = "patchOptions")]
        public PatchOptions PatchOptions { get; set; }
        
        /// <value>
        /// The administrator password of the primary database in this Data Guard association.
        /// <br/>
        /// **The password MUST be the same as the primary admin password.**
        /// 
        /// </value>
        [JsonProperty(PropertyName = "databaseAdminPassword")]
        public string DatabaseAdminPassword { get; set; }
                ///
        /// <value>
        /// The protection mode of this Data Guard. For more information, see
        /// [Oracle Data Guard Protection Modes](http://docs.oracle.com/database/122/SBYDB/oracle-data-guard-protection-modes.htm#SBYDB02000)
        /// in the Oracle Data Guard documentation.
        /// 
        /// </value>
        ///
        public enum ProtectionModeEnum {
            [EnumMember(Value = "MAXIMUM_AVAILABILITY")]
            MaximumAvailability,
            [EnumMember(Value = "MAXIMUM_PERFORMANCE")]
            MaximumPerformance,
            [EnumMember(Value = "MAXIMUM_PROTECTION")]
            MaximumProtection
        };

        /// <value>
        /// The protection mode of this Data Guard. For more information, see
        /// [Oracle Data Guard Protection Modes](http://docs.oracle.com/database/122/SBYDB/oracle-data-guard-protection-modes.htm#SBYDB02000)
        /// in the Oracle Data Guard documentation.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "protectionMode")]
        [JsonConverter(typeof(StringEnumConverter))]
        public System.Nullable<ProtectionModeEnum> ProtectionMode { get; set; }
                ///
        /// <value>
        /// The redo transport type to use for this Data Guard association.  Valid values depend on the specified `protectionMode`:
        /// <br/>
        /// * MAXIMUM_AVAILABILITY - SYNC or FASTSYNC
        /// * MAXIMUM_PERFORMANCE - ASYNC
        /// * MAXIMUM_PROTECTION - SYNC
        /// <br/>
        /// For more information, see
        /// [Redo Transport Services](http://docs.oracle.com/database/122/SBYDB/oracle-data-guard-redo-transport-services.htm#SBYDB00400)
        /// in the Oracle Data Guard documentation.
        /// <br/>
        /// **IMPORTANT** - The only transport type currently supported by the Database service is ASYNC.
        /// 
        /// </value>
        ///
        public enum TransportTypeEnum {
            [EnumMember(Value = "SYNC")]
            Sync,
            [EnumMember(Value = "ASYNC")]
            Async,
            [EnumMember(Value = "FASTSYNC")]
            Fastsync
        };

        /// <value>
        /// The redo transport type to use for this Data Guard association.  Valid values depend on the specified `protectionMode`:
        /// <br/>
        /// * MAXIMUM_AVAILABILITY - SYNC or FASTSYNC
        /// * MAXIMUM_PERFORMANCE - ASYNC
        /// * MAXIMUM_PROTECTION - SYNC
        /// <br/>
        /// For more information, see
        /// [Redo Transport Services](http://docs.oracle.com/database/122/SBYDB/oracle-data-guard-redo-transport-services.htm#SBYDB00400)
        /// in the Oracle Data Guard documentation.
        /// <br/>
        /// **IMPORTANT** - The only transport type currently supported by the Database service is ASYNC.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "transportType")]
        [JsonConverter(typeof(StringEnumConverter))]
        public System.Nullable<TransportTypeEnum> TransportType { get; set; }
        
        /// <value>
        /// True if active Data Guard is enabled.
        /// </value>
        [JsonProperty(PropertyName = "isActiveDataGuardEnabled")]
        public System.Nullable<bool> IsActiveDataGuardEnabled { get; set; }
        
        [JsonProperty(PropertyName = "autoFailoverConfiguration")]
        public AutoFailoverConfiguration AutoFailoverConfiguration { get; set; }
        
    }
}
