/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace Oci.DatabaseService.Models
{
    /// <summary>
    /// The update should be applied on the database for the selected version scheme.
    /// 
    /// </summary>
    [JsonConverter(typeof(VersionSchemeDetailsModelConverter))]
    public class VersionSchemeDetails 
    {
                ///
        /// <value>
        /// The update should be applied on the database for the selected version scheme.
        /// 
        /// </value>
        ///
        public enum SourceEnum {
            [EnumMember(Value = "VERSION_SERIES")]
            VersionSeries
        };

        
    }

    public class VersionSchemeDetailsModelConverter : JsonConverter
    {
        private static NLog.Logger logger = NLog.LogManager.GetCurrentClassLogger();
        public override bool CanWrite => false;
        public override bool CanRead => true;
        public override bool CanConvert(System.Type type)
        {
            return type == typeof(VersionSchemeDetails);
        }
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            throw new System.InvalidOperationException("Use default serialization.");
        }

        public override object ReadJson(JsonReader reader, System.Type objectType, object existingValue, JsonSerializer serializer)
        {
            var jsonObject = JObject.Load(reader);
            var obj = default(VersionSchemeDetails);
            var discriminator = jsonObject["source"].Value<string>();
            switch (discriminator)
            {
                case "VERSION_SERIES":
                    obj = new VersionSchemeFromVersionSeriesDetails();
                    break;
            }
            if (obj != null)
            {
                serializer.Populate(jsonObject.CreateReader(), obj);
            }
            else
            {
                logger.Warn($"The type {discriminator} is not present under VersionSchemeDetails! Returning null value.");
            }
            return obj;
        }
    }
}
