/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Oci.ApmconfigService.Models;

namespace Oci.ApmconfigService.Requests
{
    /// <example>
    /// Click <a href="https://docs.oracle.com/en-us/iaas/tools/dot-net-examples/latest/apmconfig/PutDataFile.cs.html">here</a> to see an example of how to use PutDataFile request.
    /// </example>
    public class PutDataFileRequest : Oci.Common.IOciRequest
    {
        
        /// <value>
        /// The data file to be uploaded.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "PutDataFileBody is required.")]
        [Oci.Common.Http.HttpConverter(Oci.Common.Http.TargetEnum.Body)]
        public System.IO.Stream PutDataFileBody { get; set; }
        
        /// <value>
        /// The name of the data file.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "DataFileName is required.")]
        [Oci.Common.Http.HttpConverter(Oci.Common.Http.TargetEnum.Path, "dataFileName")]
        public string DataFileName { get; set; }
        
        /// <value>
        /// The APM Domain ID the request is intended for.
        /// 
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "ApmDomainId is required.")]
        [Oci.Common.Http.HttpConverter(Oci.Common.Http.TargetEnum.Query, "apmDomainId")]
        public string ApmDomainId { get; set; }
        
        /// <value>
        /// The type of the data file.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "ApmType is required.")]
        [Oci.Common.Http.HttpConverter(Oci.Common.Http.TargetEnum.Query, "apmType")]
        public string ApmType { get; set; }
        
        /// <value>
        /// Optional base64-encoded MD5 hash of the request body. If provided, the server will perform
        /// a data integrity check by computing the MD5 of the received content and comparing it to the
        /// supplied value.
        /// <br/>
        /// If the values do not match, the request will be rejected with an HTTP 400 error and a message such as:
        /// <br/>
        /// \"The computed MD5 of the request body (ACTUAL_MD5) does not match the Content-MD5 header (HEADER_MD5)\"
        /// 
        /// </value>
        [Oci.Common.Http.HttpConverter(Oci.Common.Http.TargetEnum.Header, "Content-MD5")]
        public string ContentMD5 { get; set; }
        
        /// <value>
        /// Optional parameter specifying the media type (MIME type) of the request or response body.
        /// If not specified, the default is `application/octet-stream`.
        /// <br/>
        /// This value can be used by recipients to determine how to interpret or render the content.
        /// 
        /// </value>
        [Oci.Common.Http.HttpConverter(Oci.Common.Http.TargetEnum.Header, "Content-Type")]
        public string ContentType { get; set; }
        
        /// <value>
        /// Optional parameter that indicates the natural language of the content.
        /// This value can be used by clients or intermediaries to select or display content based on language preferences.
        /// 
        /// </value>
        [Oci.Common.Http.HttpConverter(Oci.Common.Http.TargetEnum.Header, "Content-Language")]
        public string ContentLanguage { get; set; }
        
        /// <value>
        /// Optional parameter indicating the content encodings applied to the request body (e.g., gzip, deflate).
        /// This value can be used by recipients to determine how to decode the content.
        /// 
        /// </value>
        [Oci.Common.Http.HttpConverter(Oci.Common.Http.TargetEnum.Header, "Content-Encoding")]
        public string ContentEncoding { get; set; }
        
        /// <value>
        /// Optional parameter that provides presentation information for how the content should be displayed or handled by the recipient.
        /// <br/>
        /// For example, to prompt a file download with a custom filename:
        /// `attachment; filename=\"example.txt\"`
        /// 
        /// </value>
        [Oci.Common.Http.HttpConverter(Oci.Common.Http.TargetEnum.Header, "Content-Disposition")]
        public string ContentDisposition { get; set; }
        
        /// <value>
        /// A string containing a JSON-encoded object with metadata related to the uploaded file or resource.
        /// Example:   {&quot;fileName&quot;:&quot;report.pdf&quot;,&quot;uploader&quot;:&quot;jane.doe&quot;,&quot;category&quot;:&quot;financial&quot;}
        /// </value>
        [Oci.Common.Http.HttpConverter(Oci.Common.Http.TargetEnum.Header, "metadata")]
        public string Metadata { get; set; }
        
        /// <value>
        /// A token that uniquely identifies a request so it can be retried in case of a timeout or
        /// server error without risk of executing that same action again. Retry tokens expire after 24
        /// hours, but can be invalidated before then due to conflicting operations. For example, if a resource
        /// has been deleted and purged from the system, then a retry of the original creation request
        /// might be rejected.
        /// 
        /// </value>
        [Oci.Common.Http.HttpConverter(Oci.Common.Http.TargetEnum.Header, "opc-retry-token")]
        public string OpcRetryToken { get; set; }
        
        /// <value>
        /// The client request ID for tracing.
        /// </value>
        [Oci.Common.Http.HttpConverter(Oci.Common.Http.TargetEnum.Header, "opc-client-request-id")]
        public string OpcClientRequestId { get; set; }
    }
}
