/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.DataccService.Models
{
    /// <summary>
    /// Capacity details of the Database Infrastructure.
    /// </summary>
    public class ComputeCapacityDetails 
    {
        
        /// <value>
        /// Total CPU cores count.
        /// </value>
        [JsonProperty(PropertyName = "totalCores")]
        public System.Nullable<int> TotalCores { get; set; }
        
        /// <value>
        /// Total CPU cores count allocated..
        /// </value>
        [JsonProperty(PropertyName = "allocatedCores")]
        public System.Nullable<int> AllocatedCores { get; set; }
        
        /// <value>
        /// Total Reserved CPU cores count.
        /// </value>
        [JsonProperty(PropertyName = "reservedCores")]
        public System.Nullable<int> ReservedCores { get; set; }
        
        /// <value>
        /// Total available CPU cores count.
        /// </value>
        [JsonProperty(PropertyName = "availableCores")]
        public System.Nullable<int> AvailableCores { get; set; }
        
        /// <value>
        /// Total memory allocated, in gigabytes (GB).
        /// </value>
        [JsonProperty(PropertyName = "totalMemoryInGBs")]
        public System.Nullable<long> TotalMemoryInGBs { get; set; }
        
        /// <value>
        /// Memory allocated to Oracle database virtual machine cluster or Instance, in gigabytes (GB).
        /// </value>
        [JsonProperty(PropertyName = "usedMemoryInGBs")]
        public System.Nullable<long> UsedMemoryInGBs { get; set; }
        
        /// <value>
        /// Reserved memory, in gigabytes (GB).
        /// </value>
        [JsonProperty(PropertyName = "reservedMemoryInGBs")]
        public System.Nullable<long> ReservedMemoryInGBs { get; set; }
        
        /// <value>
        /// Available memory, in gigabytes (GB).
        /// </value>
        [JsonProperty(PropertyName = "availableMemoryInGBs")]
        public System.Nullable<long> AvailableMemoryInGBs { get; set; }
        
    }
}
