/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.DataccService.Models
{
    /// <summary>
    /// Request to create Database Infrastructure resource.
    /// 
    /// </summary>
    public class CreateInfrastructureDetails 
    {
        
        /// <value>
        /// Database Infrastructure description.
        /// </value>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }
        
        /// <value>
        /// The [OCID](https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the compartment.
        /// 
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "CompartmentId is required.")]
        [JsonProperty(PropertyName = "compartmentId")]
        public string CompartmentId { get; set; }
        
        /// <value>
        /// The user-friendly name for the Database Infrastructure. The name does not need to be unique.
        /// 
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "DisplayName is required.")]
        [JsonProperty(PropertyName = "displayName")]
        public string DisplayName { get; set; }
        
        /// <value>
        /// Database Infrastructure System Model specification. The system model determines the model of the Database Infrastructure hardware to be used.
        /// 
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "SystemModel is required.")]
        [JsonProperty(PropertyName = "systemModel")]
        [JsonConverter(typeof(StringEnumConverter))]
        public System.Nullable<SystemModelEnum> SystemModel { get; set; }
        
        /// <value>
        /// The shape of the Database Infrastructure. The shape determines the amount of CPU, storage, and memory resources allocated to the instance.
        /// 
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "Shape is required.")]
        [JsonProperty(PropertyName = "shape")]
        [JsonConverter(typeof(StringEnumConverter))]
        public System.Nullable<ShapeEnum> Shape { get; set; }
        
        /// <value>
        /// The IP address for the first control plane server.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "CloudControlPlaneServer1 is required.")]
        [JsonProperty(PropertyName = "cloudControlPlaneServer1")]
        public string CloudControlPlaneServer1 { get; set; }
        
        /// <value>
        /// The IP address for the second control plane server.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "CloudControlPlaneServer2 is required.")]
        [JsonProperty(PropertyName = "cloudControlPlaneServer2")]
        public string CloudControlPlaneServer2 { get; set; }
        
        /// <value>
        /// The netmask for the control plane network.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "Netmask is required.")]
        [JsonProperty(PropertyName = "netmask")]
        public string Netmask { get; set; }
        
        /// <value>
        /// The gateway for the control plane network.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "Gateway is required.")]
        [JsonProperty(PropertyName = "gateway")]
        public string Gateway { get; set; }
        
        /// <value>
        /// The CIDR block for the system network. The system network is a private network in Database Infrastructure and is not connected to your corporate network. The system network is used for storage (ASM) traffic, high-performance interconnect traffic and administration of infrastructure components.
        /// </value>
        [JsonProperty(PropertyName = "adminNetworkcidr")]
        public string AdminNetworkcidr { get; set; }
        
        /// <value>
        /// Percentage of disk space assigned for DATA disk group. Remaining disk space will get assiged to RECO disk group
        /// </value>
        [JsonProperty(PropertyName = "dataDiskPercentage")]
        public System.Nullable<int> DataDiskPercentage { get; set; }
        
        /// <value>
        /// The list of contacts for the Database Infrastructure.
        /// </value>
        [JsonProperty(PropertyName = "contacts")]
        public System.Collections.Generic.List<InfrastructureContact> Contacts { get; set; }
        
        /// <value>
        /// The list of DNS server IP addresses. Maximum of 3 allowed.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "DnsServers is required.")]
        [JsonProperty(PropertyName = "dnsServers")]
        public System.Collections.Generic.List<string> DnsServers { get; set; }
        
        /// <value>
        /// The list of NTP server IP addresses. Maximum of 3 allowed.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "NtpServers is required.")]
        [JsonProperty(PropertyName = "ntpServers")]
        public System.Collections.Generic.List<string> NtpServers { get; set; }
        
        /// <value>
        /// The network bonding mode for Client networks for the Database Infrastructure.
        /// </value>
        [JsonProperty(PropertyName = "clientNetworkBondingMode")]
        [JsonConverter(typeof(StringEnumConverter))]
        public System.Nullable<NetworkBondingMode> ClientNetworkBondingMode { get; set; }
        
        /// <value>
        /// The network bonding mode for Backup networks for the Database Infrastructure.
        /// </value>
        [JsonProperty(PropertyName = "backupNetworkBondingMode")]
        [JsonConverter(typeof(StringEnumConverter))]
        public System.Nullable<NetworkBondingMode> BackupNetworkBondingMode { get; set; }
        
        /// <value>
        /// The network bonding mode for CPS networks for the Database Infrastructure.
        /// </value>
        [JsonProperty(PropertyName = "cpsNetworkBondingMode")]
        [JsonConverter(typeof(StringEnumConverter))]
        public System.Nullable<NetworkBondingMode> CpsNetworkBondingMode { get; set; }
        
        /// <value>
        /// The network bonding interface for client network for the Database Infrastructure.
        /// </value>
        [JsonProperty(PropertyName = "clientNetworkBondingInterface")]
        [JsonConverter(typeof(StringEnumConverter))]
        public System.Nullable<NetworkBondingInterfaceEnum> ClientNetworkBondingInterface { get; set; }
        
        /// <value>
        /// The network bonding interface for backup network for the Database Infrastructure.
        /// </value>
        [JsonProperty(PropertyName = "backupNetworkBondingInterface")]
        [JsonConverter(typeof(StringEnumConverter))]
        public System.Nullable<NetworkBondingInterfaceEnum> BackupNetworkBondingInterface { get; set; }
        
        /// <value>
        /// The network bonding interface for CPS network for the Database Infrastructure.
        /// </value>
        [JsonProperty(PropertyName = "cpsNetworkBondingInterface")]
        [JsonConverter(typeof(StringEnumConverter))]
        public System.Nullable<NetworkBondingInterfaceEnum> CpsNetworkBondingInterface { get; set; }
        
        /// <value>
        /// The amount of storage (in GB) in the DATA disk group that is reserved for creating local storage for VM Clusters and application VMs.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "acfsFileSystemStorageInGbs")]
        public System.Double AcfsFileSystemStorageInGbs { get; set; }
        
        /// <value>
        /// The corporate network proxy for access to the control plane network. Oracle recommends using an HTTPS proxy when possible
        /// for enhanced security.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "corporateProxy")]
        public string CorporateProxy { get; set; }
        
        /// <value>
        /// The CPS network VLAN ID.
        /// </value>
        [JsonProperty(PropertyName = "vlanId")]
        public string VlanId { get; set; }
        
        [JsonProperty(PropertyName = "maintenanceWindow")]
        public MaintenanceWindow MaintenanceWindow { get; set; }
        
        /// <value>
        /// Simple key-value pair that is applied without any predefined name, type or scope. This tag option exists for cross-compatibility only.
        /// Example: {&quot;bar-key&quot;: &quot;value&quot;}
        /// </value>
        [JsonProperty(PropertyName = "freeformTags")]
        public System.Collections.Generic.Dictionary<string, string> FreeformTags { get; set; }
        
        /// <value>
        /// Defined tags for this resource. Each key is predefined and scoped to a namespace.
        /// Example: {&quot;foo-namespace&quot;: {&quot;bar-key&quot;: &quot;value&quot;}}
        /// </value>
        [JsonProperty(PropertyName = "definedTags")]
        public System.Collections.Generic.Dictionary<string, System.Collections.Generic.Dictionary<string, System.Object>> DefinedTags { get; set; }
        
    }
}
