/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.DataccService.Models
{
    /// <summary>
    /// Capacity details of the Storage disk group.
    /// </summary>
    public class StorageCapacityDetails 
    {
        
        /// <value>
        /// The Disk redundancy for Database Infrastructure storage.
        /// </value>
        [JsonProperty(PropertyName = "storageDiskRedundancy")]
        [JsonConverter(typeof(Oci.Common.Utils.ResponseEnumConverter))]
        public System.Nullable<StorageDiskRedundancy> StorageDiskRedundancy { get; set; }
        
        /// <value>
        /// Disk group name.
        /// </value>
        [JsonProperty(PropertyName = "diskGroup")]
        public string DiskGroup { get; set; }
        
        /// <value>
        /// The total amount of physical disk space available in a disk group, in gigabytes (GB).
        /// </value>
        [JsonProperty(PropertyName = "phyTotalSpaceInGBs")]
        public System.Nullable<long> PhyTotalSpaceInGBs { get; set; }
        
        /// <value>
        /// The total amount of physical disk space that is reserved for system use in a disk group, in gigabytes (GB).
        /// </value>
        [JsonProperty(PropertyName = "phyReservedSpaceInGBs")]
        public System.Nullable<long> PhyReservedSpaceInGBs { get; set; }
        
        /// <value>
        /// The total amount of physical disk space that is currently available for use in a disk group, in gigabytes (GB).
        /// </value>
        [JsonProperty(PropertyName = "phyFreeSpaceInGBs")]
        public System.Nullable<long> PhyFreeSpaceInGBs { get; set; }
        
        /// <value>
        /// The total amount of logical disk space that is currently available for use in a disk group, in gigabytes (GB).
        /// </value>
        [JsonProperty(PropertyName = "logicalFreeSpaceInGBs")]
        public System.Nullable<long> LogicalFreeSpaceInGBs { get; set; }
        
    }
}
