/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.MarketplacepublisherService.Models
{
    /// <summary>
    /// Listing revision details for AI agent listings
    /// </summary>
    public class AdminAiAgentListingRevision : AdminListingRevision
    {
        
        [JsonProperty(PropertyName = "versionDetails")]
        public VersionDetails VersionDetails { get; set; }
        
        /// <value>
        /// Custom link to the listing
        /// </value>
        [JsonProperty(PropertyName = "vanityUrl")]
        public string VanityUrl { get; set; }
        
        /// <value>
        /// Measurable or compelling value of the agent
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "KeyBenefits is required.")]
        [JsonProperty(PropertyName = "keyBenefits")]
        public string KeyBenefits { get; set; }
        
        /// <value>
        /// Capture asset competitive differentiator
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "CompetitiveDifferentiators is required.")]
        [JsonProperty(PropertyName = "competitiveDifferentiators")]
        public string CompetitiveDifferentiators { get; set; }
        
        /// <value>
        /// Target audience for the asset
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "TargetAudience is required.")]
        [JsonProperty(PropertyName = "targetAudience")]
        public string TargetAudience { get; set; }
        
        /// <value>
        /// List of industries subscribed by listing.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "Industries is required.")]
        [JsonProperty(PropertyName = "industries")]
        public System.Collections.Generic.List<string> Industries { get; set; }
        
        /// <value>
        /// Support details based on geographic location
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "GeoLocations is required.")]
        [JsonProperty(PropertyName = "geoLocations")]
        public System.Collections.Generic.List<GeoLocation> GeoLocations { get; set; }
                ///
        /// <value>
        /// Agent asset type
        /// </value>
        ///
        public enum AssetTypeEnum {
            /// This value is used if a service returns a value for this enum that is not recognized by this version of the SDK.
            [EnumMember(Value = null)]
            UnknownEnumValue,
            [EnumMember(Value = "FOUNDATIONAL")]
            Foundational,
            [EnumMember(Value = "TEAM")]
            Team,
            [EnumMember(Value = "WORKFLOW")]
            Workflow,
            [EnumMember(Value = "APPLICATION")]
            Application,
            [EnumMember(Value = "CONNECTOR")]
            Connector
        };

        /// <value>
        /// Agent asset type
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "AssetType is required.")]
        [JsonProperty(PropertyName = "assetType")]
        [JsonConverter(typeof(Oci.Common.Utils.ResponseEnumConverter))]
        public System.Nullable<AssetTypeEnum> AssetType { get; set; }
                ///
        /// <value>
        /// Work area that surfaces the AI agent
        /// </value>
        ///
        public enum LocationEnum {
            /// This value is used if a service returns a value for this enum that is not recognized by this version of the SDK.
            [EnumMember(Value = null)]
            UnknownEnumValue,
            [EnumMember(Value = "SEEDED")]
            Seeded,
            [EnumMember(Value = "LEAD_GEN")]
            LeadGen
        };

        /// <value>
        /// Work area that surfaces the AI agent
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "Location is required.")]
        [JsonProperty(PropertyName = "location")]
        [JsonConverter(typeof(Oci.Common.Utils.ResponseEnumConverter))]
        public System.Nullable<LocationEnum> Location { get; set; }
        
        /// <value>
        /// List of products subscribed by listing.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "Products is required.")]
        [JsonProperty(PropertyName = "products")]
        public System.Collections.Generic.List<AdminListingProduct> Products { get; set; }
        
        [JsonProperty(PropertyName = "listingType")]
        private readonly string listingType = "AI_AGENT";
    }
}
