/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.MarketplacepublisherService.Models
{
    /// <summary>
    /// A listing SKUs and meter information attached by marketplace admin.
    /// </summary>
    public class ListingPart 
    {
        
        /// <value>
        /// The SKU/part name.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "Sku is required.")]
        [JsonProperty(PropertyName = "sku")]
        public string Sku { get; set; }
        
        /// <value>
        /// Unique identifier of the pricing plan.
        /// </value>
        [JsonProperty(PropertyName = "pricingPlanKey")]
        public string PricingPlanKey { get; set; }
                ///
        /// <value>
        /// The billing model for SaaS paid listing parts.
        /// </value>
        ///
        public enum BillingModelEnum {
            /// This value is used if a service returns a value for this enum that is not recognized by this version of the SDK.
            [EnumMember(Value = null)]
            UnknownEnumValue,
            [EnumMember(Value = "FLAT_RATE")]
            FlatRate,
            [EnumMember(Value = "USAGE_BASED")]
            UsageBased
        };

        /// <value>
        /// The billing model for SaaS paid listing parts.
        /// </value>
        [JsonProperty(PropertyName = "billingModel")]
        [JsonConverter(typeof(Oci.Common.Utils.ResponseEnumConverter))]
        public System.Nullable<BillingModelEnum> BillingModel { get; set; }
        
        /// <value>
        /// The part's metric.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "MetricType is required.")]
        [JsonProperty(PropertyName = "metricType")]
        [JsonConverter(typeof(Oci.Common.Utils.ResponseEnumConverter))]
        public System.Nullable<MetricType> MetricType { get; set; }
        
        /// <value>
        /// rate allocation, these are calculated based on rate information at listing revision.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "RateAllocation is required.")]
        [JsonProperty(PropertyName = "rateAllocation")]
        public System.Nullable<float> RateAllocation { get; set; }
        
        /// <value>
        /// Identifies whether part has Gov SKU.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "HasGovSku is required.")]
        [JsonProperty(PropertyName = "hasGovSku")]
        public System.Nullable<bool> HasGovSku { get; set; }
        
        /// <value>
        /// List of meters associated with the part.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "Meters is required.")]
        [JsonProperty(PropertyName = "meters")]
        public System.Collections.Generic.List<ListingMeter> Meters { get; set; }
        
    }
}
