/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.MarketplacepublisherService.Models
{
    /// <summary>
    /// Partner Portal Options.
    /// </summary>
    public class PartnerPortalOptions 
    {
        
        /// <value>
        /// Enable Oracle Cloud Marketplace Publisher Agreement validity check for partner before listing is published.
        /// </value>
        [JsonProperty(PropertyName = "isEnablePublisherAgreementCheckBeforeListingPublish")]
        public System.Nullable<bool> IsEnablePublisherAgreementCheckBeforeListingPublish { get; set; }
        
        /// <value>
        /// Enable OPN membership status check for partner before listing is published.
        /// </value>
        [JsonProperty(PropertyName = "isEnableOpnMembershipStatusCheckBeforeListingPublish")]
        public System.Nullable<bool> IsEnableOpnMembershipStatusCheckBeforeListingPublish { get; set; }
        
        /// <value>
        /// Enable the Reports feature for this Partner.
        /// </value>
        [JsonProperty(PropertyName = "isEnableReports")]
        public System.Nullable<bool> IsEnableReports { get; set; }
        
        /// <value>
        /// Enable the private listing feature for this Partner.
        /// </value>
        [JsonProperty(PropertyName = "isEnablePrivateListing")]
        public System.Nullable<bool> IsEnablePrivateListing { get; set; }
        
        /// <value>
        /// Enable Auto-publish on listing submit for this partner for Lead generation listings.
        /// </value>
        [JsonProperty(PropertyName = "isEnableAutoPublishOnSubmitForLeadGenListings")]
        public System.Nullable<bool> IsEnableAutoPublishOnSubmitForLeadGenListings { get; set; }
        
        /// <value>
        /// Disable Auto-publish option visibility for listing submit flow. Defaults to false when unset.
        /// </value>
        [JsonProperty(PropertyName = "isDisableAutoPublishOnSubmit")]
        public System.Nullable<bool> IsDisableAutoPublishOnSubmit { get; set; }
        
        /// <value>
        /// Enable Auto approval options for new listings - Include OCI Application listings with Image artifact.
        /// </value>
        [JsonProperty(PropertyName = "isEnableAutoApprovalForImageArtifactNewAppListings")]
        public System.Nullable<bool> IsEnableAutoApprovalForImageArtifactNewAppListings { get; set; }
        
        /// <value>
        /// Enable Auto approval options for new listings - Include OCI Application listings with Terraform artifact.
        /// </value>
        [JsonProperty(PropertyName = "isEnableAutoApprovalForTerraformArtifactNewAppListings")]
        public System.Nullable<bool> IsEnableAutoApprovalForTerraformArtifactNewAppListings { get; set; }
        
        /// <value>
        /// Enable Auto approval options for new listings - Include OCI Paid Application listings.
        /// </value>
        [JsonProperty(PropertyName = "isEnableAutoApprovalForNewPaidAppListings")]
        public System.Nullable<bool> IsEnableAutoApprovalForNewPaidAppListings { get; set; }
        
        /// <value>
        /// Enable Auto approval options for new listings - Include Lead generation listings.
        /// </value>
        [JsonProperty(PropertyName = "isEnableAutoApprovalForNewLeadGenListings")]
        public System.Nullable<bool> IsEnableAutoApprovalForNewLeadGenListings { get; set; }
        
        /// <value>
        /// Disable Auto approval options for versioned listings - Include OCI Application listings with Image artifact.
        /// </value>
        [JsonProperty(PropertyName = "isDisableAutoApprovalForImageArtifactVersionedAppListings")]
        public System.Nullable<bool> IsDisableAutoApprovalForImageArtifactVersionedAppListings { get; set; }
        
        /// <value>
        /// Disable Auto approval options for versioned listings - Include OCI Application listings with Terraform artifact.
        /// </value>
        [JsonProperty(PropertyName = "isDisableAutoApprovalForTerraformArtifactVersionedAppListings")]
        public System.Nullable<bool> IsDisableAutoApprovalForTerraformArtifactVersionedAppListings { get; set; }
        
        /// <value>
        /// Disable Auto approval options for versioned listings - Include OCI Application listings with Container artifact.
        /// </value>
        [JsonProperty(PropertyName = "isDisableAutoApprovalForContainerArtifactVersionedAppListings")]
        public System.Nullable<bool> IsDisableAutoApprovalForContainerArtifactVersionedAppListings { get; set; }
        
        /// <value>
        /// Disable Auto approval options for versioned listings - Include OCI Application listings with Helm chart artifact.
        /// </value>
        [JsonProperty(PropertyName = "isDisableAutoApprovalForHelmChartVersionedAppListings")]
        public System.Nullable<bool> IsDisableAutoApprovalForHelmChartVersionedAppListings { get; set; }
        
        /// <value>
        /// Enable Auto approval options for versioned listings - Include Service listings.
        /// </value>
        [JsonProperty(PropertyName = "isEnableAutoApprovalForServiceVersionedListings")]
        public System.Nullable<bool> IsEnableAutoApprovalForServiceVersionedListings { get; set; }
        
        /// <value>
        /// Enable Auto approval options for versioned listings - Include Fusion AiAgent listings.
        /// </value>
        [JsonProperty(PropertyName = "isEnableAutoApprovalForFusionAiAgentVersionedListings")]
        public System.Nullable<bool> IsEnableAutoApprovalForFusionAiAgentVersionedListings { get; set; }
        
        /// <value>
        /// Enable Auto approval options for versioned listings - Include Lead generation listings.
        /// </value>
        [JsonProperty(PropertyName = "isEnableAutoApprovalForLeadGenVersionedListings")]
        public System.Nullable<bool> IsEnableAutoApprovalForLeadGenVersionedListings { get; set; }
        
        /// <value>
        /// Disable Auto approval options for versioned listings - Include SaaS listings.
        /// </value>
        [JsonProperty(PropertyName = "isDisableAutoApprovalForSaaSVersionedListings")]
        public System.Nullable<bool> IsDisableAutoApprovalForSaaSVersionedListings { get; set; }
        
        /// <value>
        /// Disable Auto approval options for versioned listings - Include Paid App listings.
        /// </value>
        [JsonProperty(PropertyName = "isDisableAutoApprovalForPaidAppVersionedListings")]
        public System.Nullable<bool> IsDisableAutoApprovalForPaidAppVersionedListings { get; set; }
        
    }
}
