/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.MarketplaceprivateofferService.Models
{
    /// <summary>
    /// The details for creating a new offer quote attachment.
    /// </summary>
    public class CreateQuoteAttachmentDetails 
    {
        
        /// <value>
        /// Base64-encoded file to attach to the offer quote.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "FileBase64Encoded is required.")]
        [JsonProperty(PropertyName = "fileBase64Encoded")]
        public System.Byte[] FileBase64Encoded { get; set; }
        
        /// <value>
        /// The name used to refer to the uploaded data.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "DisplayName is required.")]
        [JsonProperty(PropertyName = "displayName")]
        public string DisplayName { get; set; }
        
        /// <value>
        /// The type of offer quote attachment.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "Type is required.")]
        [JsonProperty(PropertyName = "type")]
        [JsonConverter(typeof(StringEnumConverter))]
        public System.Nullable<QuoteAttachment.TypeEnum> Type { get; set; }
        
        /// <value>
        /// The recipient of the offer quote attachment.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "Recipient is required.")]
        [JsonProperty(PropertyName = "recipient")]
        [JsonConverter(typeof(StringEnumConverter))]
        public System.Nullable<QuoteAttachment.RecipientEnum> Recipient { get; set; }
        
    }
}
