/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;

namespace Oci.DatabasemigrationService.Models
{
  /// <summary>
  /// Time allowed for the application downtime.
  /// </summary>
  public enum AcceptableDowntime {
      /// This value is used if a service returns a value for this enum that is not recognized by this version of the SDK.
      [EnumMember(Value = null)]
      UnknownEnumValue,
      [EnumMember(Value = "LESS_THAN_10_MINUTES")]
      LessThan10Minutes,
      [EnumMember(Value = "LESS_THAN_1_HOUR")]
      LessThan1Hour,
      [EnumMember(Value = "LESS_THAN_4_HOURS")]
      LessThan4Hours,
      [EnumMember(Value = "LESS_THAN_8_HOURS")]
      LessThan8Hours,
      [EnumMember(Value = "LESS_THAN_12_HOURS")]
      LessThan12Hours,
      [EnumMember(Value = "LESS_THAN_1_DAY")]
      LessThan1Day,
      [EnumMember(Value = "LESS_THAN_2_DAYS")]
      LessThan2Days,
      [EnumMember(Value = "MORE_THAN_2_DAYS")]
      MoreThan2Days
  }
}
