/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.DatabasemigrationService.Models
{
    /// <summary>
    /// Pre-Migration extended advisor report summary.
    /// 
    /// </summary>
    public class AdvisorCheckSummary 
    {
        
        /// <value>
        /// Number of PASS results in the extended advisor report.
        /// 
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "PassResultsTotalCount is required.")]
        [JsonProperty(PropertyName = "passResultsTotalCount")]
        public System.Nullable<int> PassResultsTotalCount { get; set; }
        
        /// <value>
        /// Number of INFORMATIONAL results in the extended advisor report.
        /// 
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "InformationalResultsTotalCount is required.")]
        [JsonProperty(PropertyName = "informationalResultsTotalCount")]
        public System.Nullable<int> InformationalResultsTotalCount { get; set; }
        
        /// <value>
        /// Number of WARNING results in the extended advisor report.
        /// 
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "WarningResultsTotalCount is required.")]
        [JsonProperty(PropertyName = "warningResultsTotalCount")]
        public System.Nullable<int> WarningResultsTotalCount { get; set; }
        
        /// <value>
        /// Number of BLOCKER results in the extended advisor report.
        /// 
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "BlockerResultsTotalCount is required.")]
        [JsonProperty(PropertyName = "blockerResultsTotalCount")]
        public System.Nullable<int> BlockerResultsTotalCount { get; set; }
        
        /// <value>
        /// Number of FATAL results in the extended advisor report.
        /// 
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "FatalResultsTotalCount is required.")]
        [JsonProperty(PropertyName = "fatalResultsTotalCount")]
        public System.Nullable<int> FatalResultsTotalCount { get; set; }
        
    }
}
