/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.DatabasemigrationService.Models
{
    /// <summary>
    /// Assessor Check Summary
    /// </summary>
    public class AssessorCheckSummary 
    {
        
        /// <value>
        /// The Name of the Check.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "Name is required.")]
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }
        
        /// <value>
        /// A user-friendly name. Does not have to be unique, and it's changeable. 
        /// Avoid entering confidential information.
        /// 
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "DisplayName is required.")]
        [JsonProperty(PropertyName = "displayName")]
        public string DisplayName { get; set; }
        
        /// <value>
        /// A user-friendly description. Does not have to be unique, and it's changeable. 
        /// Avoid entering confidential information.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }
        
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "AssessorCheckGroup is required.")]
        [JsonProperty(PropertyName = "assessorCheckGroup")]
        public AssessorCheckGroup AssessorCheckGroup { get; set; }
        
        /// <value>
        /// The Help URL.
        /// </value>
        [JsonProperty(PropertyName = "helpLinkUrl")]
        public string HelpLinkUrl { get; set; }
        
        /// <value>
        /// The Help link text.
        /// </value>
        [JsonProperty(PropertyName = "helpLinkText")]
        public string HelpLinkText { get; set; }
        
        /// <value>
        /// The current state of the Assessor Check.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "AssessorCheckState is required.")]
        [JsonProperty(PropertyName = "assessorCheckState")]
        [JsonConverter(typeof(Oci.Common.Utils.ResponseEnumConverter))]
        public System.Nullable<AssessorCheckStates> AssessorCheckState { get; set; }
        
        [JsonProperty(PropertyName = "checkAction")]
        public AssessorCheckAction CheckAction { get; set; }
        
        /// <value>
        /// Pre-Migration \u0441heck id.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "key")]
        public string Key { get; set; }
        
        /// <value>
        /// Description of the issue.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "issue")]
        public string Issue { get; set; }
        
        /// <value>
        /// Impact of the issue on data migration.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "impact")]
        public string Impact { get; set; }
        
        /// <value>
        /// Fixing the issue.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "action")]
        public string Action { get; set; }
        
        /// <value>
        /// The path to the fixup script for this check.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "fixupScriptLocation")]
        public string FixupScriptLocation { get; set; }
        
        /// <value>
        /// If false, objects cannot be excluded from migration.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "isExclusionAllowed")]
        public System.Nullable<bool> IsExclusionAllowed { get; set; }
        
        [JsonProperty(PropertyName = "metadata")]
        public ObjectMetadata Metadata { get; set; }
        
        /// <value>
        /// Array of the column of the objects table.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "columns")]
        public System.Collections.Generic.List<AdvisorReportCheckColumn> Columns { get; set; }
        
        /// <value>
        /// Number of database objects to migrate.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "objectCount")]
        public System.Nullable<int> ObjectCount { get; set; }
        
        /// <value>
        /// The objects display name.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "objectsDisplayName")]
        public string ObjectsDisplayName { get; set; }
        
        [JsonProperty(PropertyName = "logLocation")]
        public LogLocationBucketDetails LogLocation { get; set; }
        
    }
}
