/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;

namespace Oci.DatabasemigrationService.Models
{
  /// <summary>
  /// The size of a source database.
  /// </summary>
  public enum DatabaseDataSize {
      /// This value is used if a service returns a value for this enum that is not recognized by this version of the SDK.
      [EnumMember(Value = null)]
      UnknownEnumValue,
      [EnumMember(Value = "LESS_THAN_1GB")]
      LessThan1Gb,
      [EnumMember(Value = "GB_1_10")]
      Gb110,
      [EnumMember(Value = "GB_10_50")]
      Gb1050,
      [EnumMember(Value = "GB_50_100")]
      Gb50100,
      [EnumMember(Value = "GB_100_500")]
      Gb100500,
      [EnumMember(Value = "GB_500_TB_1")]
      Gb500Tb1,
      [EnumMember(Value = "TB_1_3")]
      Tb13,
      [EnumMember(Value = "TB_3_10")]
      Tb310,
      [EnumMember(Value = "TB_10_50")]
      Tb1050,
      [EnumMember(Value = "GREATER_THAN_50TB")]
      GreaterThan50Tb
  }
}
