/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.DatabasemigrationService.Models
{
    /// <summary>
    /// Technology sub-type e.g. ADW_SHARED and database versions corresponding to the sub-type.
    /// </summary>
    public class DatabaseTechnologySubType 
    {
        
        /// <value>
        /// Technology sub-type e.g. ADW_SHARED.
        /// </value>
        [JsonProperty(PropertyName = "technologySubType")]
        public string TechnologySubType { get; set; }
        
        /// <value>
        /// A user-friendly name. Does not have to be unique, and it's changeable. 
        /// Avoid entering confidential information.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "technologySubTypeDisplayName")]
        public string TechnologySubTypeDisplayName { get; set; }
        
        /// <value>
        /// Array of database versions
        /// </value>
        [JsonProperty(PropertyName = "databaseVersions")]
        public System.Collections.Generic.List<string> DatabaseVersions { get; set; }
        
    }
}
