/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;

namespace Oci.DatabasemigrationService.Models
{
  /// <summary>
  /// Possible network speed values.
  /// </summary>
  public enum NetworkSpeedMegabitPerSecond {
      /// This value is used if a service returns a value for this enum that is not recognized by this version of the SDK.
      [EnumMember(Value = null)]
      UnknownEnumValue,
      [EnumMember(Value = "MBPS_10")]
      Mbps10,
      [EnumMember(Value = "MBPS_100")]
      Mbps100,
      [EnumMember(Value = "MBPS_1000")]
      Mbps1000,
      [EnumMember(Value = "MBPS_2500")]
      Mbps2500,
      [EnumMember(Value = "MBPS_5000")]
      Mbps5000,
      [EnumMember(Value = "MBPS_10000")]
      Mbps10000
  }
}
