/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.DatabasemigrationService.Models
{
    /// <summary>
    /// Metadata of object.
    /// 
    /// </summary>
    public class ObjectMetadata 
    {
        
        /// <value>
        /// The field that stores the owner of the object.
        /// 
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "SchemaOwnerColumn is required.")]
        [JsonProperty(PropertyName = "schemaOwnerColumn")]
        public string SchemaOwnerColumn { get; set; }
        
        /// <value>
        /// The field that stores the name of the object.
        /// 
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "ObjectNameColumn is required.")]
        [JsonProperty(PropertyName = "objectNameColumn")]
        public string ObjectNameColumn { get; set; }
        
        /// <value>
        /// The field that stores the fixed type of the object.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "objectTypeFixed")]
        public string ObjectTypeFixed { get; set; }
        
        /// <value>
        /// The field that stores the type of the object.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "objectTypeColumn")]
        public string ObjectTypeColumn { get; set; }
        
    }
}
