/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.DatabasemigrationService.Models
{
    /// <summary>
    /// Oracle offline logical migration settings.
    /// </summary>
    public class OracleOfflineLogicalMigrationSettings : OracleMigrationSettings
    {
        
        [JsonProperty(PropertyName = "dataTransferMediumDetails")]
        public OracleDataTransferMediumDetails DataTransferMediumDetails { get; set; }
        
        [JsonProperty(PropertyName = "initialLoadSettings")]
        public OracleInitialLoadSettings InitialLoadSettings { get; set; }
        
        [JsonProperty(PropertyName = "advisorSettings")]
        public OracleAdvisorSettings AdvisorSettings { get; set; }
        
        /// <value>
        /// List of Migration Parameter objects.
        /// </value>
        [JsonProperty(PropertyName = "advancedParameters")]
        public System.Collections.Generic.List<MigrationParameterDetails> AdvancedParameters { get; set; }
        
        [JsonProperty(PropertyName = "migrationMethod")]
        private readonly string migrationMethod = "OFFLINE_LOGICAL";
    }
}
