/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.DatabasemigrationService.Models
{
    /// <summary>
    /// Table row count comparison result line for Oracle migrations.
    /// 
    /// </summary>
    public class OracleDataVerificationTableRowCountSummary : DataVerificationTableRowCountSummary
    {
        
        /// <value>
        /// Time of last statistics collection in the source used for the dictionary-based row count estimate.
        /// This value is reported per row because statistics can be collected at different times per object.
        /// This timestamp is stored in UTC.
        /// 
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "TimeLastSourceStatisticsCollection is required.")]
        [JsonProperty(PropertyName = "timeLastSourceStatisticsCollection")]
        public System.Nullable<System.DateTime> TimeLastSourceStatisticsCollection { get; set; }
        
        /// <value>
        /// Time of last statistics collection in the target used for the dictionary-based row count estimate.
        /// This value is reported per row because statistics can be collected at different times per object.
        /// This timestamp is stored in UTC.
        /// 
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "TimeLastTargetStatisticsCollection is required.")]
        [JsonProperty(PropertyName = "timeLastTargetStatisticsCollection")]
        public System.Nullable<System.DateTime> TimeLastTargetStatisticsCollection { get; set; }
        
        [JsonProperty(PropertyName = "databaseCombination")]
        private readonly string databaseCombination = "ORACLE";
    }
}
