/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.MysqlService.Models
{
    /// <summary>
    /// Status information for the channel attached to the DB System.
    /// 
    /// </summary>
    public class ChannelStatusResult 
    {
        
        /// <value>
        /// The OCID of the Channel for which the status is gathered.
        /// 
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "ChannelId is required.")]
        [JsonProperty(PropertyName = "channelId")]
        public string ChannelId { get; set; }
        
        /// <value>
        /// Specifies if the channel is healthy or not. If healthy, replication target DB System is connected to the 
        /// source and no replication errors are seen.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "isHealthy")]
        public System.Nullable<bool> IsHealthy { get; set; }
        
        /// <value>
        /// Specifies if all transactions received by this channel are executed and their GTIDs are part of gtid_executed
        /// set.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "isReceivedGtidSetApplied")]
        public System.Nullable<bool> IsReceivedGtidSetApplied { get; set; }
        
        /// <value>
        /// Channel errors identified, if there are any.
        /// </value>
        [JsonProperty(PropertyName = "errors")]
        public System.Collections.Generic.List<string> Errors { get; set; }
        
        /// <value>
        /// The channel lag, with respect to the immediate source of the channel. 
        /// If the channel is configured with replication delay, the channel lag includes the replication delay.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "lagDuration")]
        public string LagDuration { get; set; }
        
    }
}
