/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.MysqlService.Models
{
    /// <summary>
    /// Properties to setup a replication channel with the source (cloned) DB system.
    /// 
    /// </summary>
    public class CreateDbSystemSourceFromDbSystemChannelDetails 
    {
        
        /// <value>
        /// The name of the replication user on the source DB system.
        /// The username has a maximum length of 96 characters. For more information,
        /// please see the [MySQL documentation](https://dev.mysql.com/doc/en/change-replication-source-to.html)
        /// 
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "SourceUsername is required.")]
        [JsonProperty(PropertyName = "sourceUsername")]
        public string SourceUsername { get; set; }
        
        /// <value>
        /// The password for the replication user. The password must be
        /// between 8 and 32 characters long, and must contain at least 1
        /// numeric character, 1 lowercase character, 1 uppercase character,
        /// and 1 special (nonalphanumeric) character.
        /// 
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "SourcePassword is required.")]
        [JsonProperty(PropertyName = "sourcePassword")]
        public string SourcePassword { get; set; }
        
        /// <value>
        /// The SSL mode of the Channel.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "SslMode is required.")]
        [JsonProperty(PropertyName = "sslMode")]
        [JsonConverter(typeof(StringEnumConverter))]
        public System.Nullable<SslMode> SslMode { get; set; }
        
        [JsonProperty(PropertyName = "sslCaCertificate")]
        public CaCertificate SslCaCertificate { get; set; }
        
        /// <value>
        /// The username for the replication applier of the created MySQL DB System.
        /// </value>
        [JsonProperty(PropertyName = "applierUsername")]
        public string ApplierUsername { get; set; }
        
    }
}
