/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.MysqlService.Models
{
    /// <summary>
    /// The status collected from the DB System.
    /// 
    /// </summary>
    public class DbSystemStatusResult 
    {
        
        /// <value>
        /// Specifies if the Read/Write endpoint of the DB System can accept client connections.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "canAcceptClientConnections")]
        public System.Nullable<bool> CanAcceptClientConnections { get; set; }
        
        /// <value>
        /// Specifies if the DB System is in offline mode based on the value of the MySQL system variable
        /// [offline_mode](https://dev.mysql.com/doc/en/server-system-variables.html#sysvar_offline_mode).
        /// If True, access is allowed only to users with specific privileges. If False, access is allowed for all MySQL
        /// user accounts.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "isInOfflineMode")]
        public System.Nullable<bool> IsInOfflineMode { get; set; }
        
        /// <value>
        /// Specifies if connected users can run write queries on the DB System.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "isWritable")]
        public System.Nullable<bool> IsWritable { get; set; }
        
        /// <value>
        /// Specifies if the single MySQL instance in a standalone DB System or all MySQL instances in a highly available
        /// DB System (excluding read replicas) are healthy.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "areAllMysqlInstancesHealthy")]
        public System.Nullable<bool> AreAllMysqlInstancesHealthy { get; set; }
        
        /// <value>
        /// Specifies if there is any MySQL instance (excluding read replicas) whose storage capacity is below [storage reserve]
        /// (https://docs.oracle.com/en-us/iaas/mysql-database/doc/health-monitor.html#GUID-C6CE25C7-B728-4C80-B548-A76B42005C83.html).
        /// 
        /// </value>
        [JsonProperty(PropertyName = "isStorageFull")]
        public System.Nullable<bool> IsStorageFull { get; set; }
        
        /// <value>
        /// The GTID set on the DB System (either GTID_EXECUTED or GTID_AVAILABLE) as specified by the gtidSetType 
        /// parameter in the request.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "gtidSet")]
        public string GtidSet { get; set; }
        
        /// <value>
        /// Specifies if the GTID set in the gtidSetToApply parameter (if provided in the request) is fully applied 
        /// on the DB System. If gtidSetToApply is not provided in the request or is \"\", this field will be empty.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "isGtidSetApplied")]
        public System.Nullable<bool> IsGtidSetApplied { get; set; }
        
        /// <value>
        /// A list showing the status of the channels attached to the DB System for the requested channel IDs.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "channelsStatus")]
        public System.Collections.Generic.List<ChannelStatusResult> ChannelsStatus { get; set; }
        
    }
}
