/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.MysqlService.Models
{
    /// <summary>
    /// Parameters for selecting which attributes to include in the DB System status.
    /// </summary>
    public class GenerateDbSystemStatusDetails 
    {
                ///
        /// <value>
        /// Specifies whether to collect the full set of GTIDs executed on the DB System 
        /// ([gtid_executed](https://dev.mysql.com/doc/en/replication-options-gtids.html#sysvar_gtid_executed)) 
        /// or the set of GTIDs available in the DB System binary logs, not part of
        /// ([gtid_purged](https://dev.mysql.com/doc/en/replication-options-gtids.html#sysvar_gtid_purged)) 
        /// (GTID_AVAILABLE, which is gtid_executed - gtid_purged).
        /// Use GTID_AVAILABLE if gtid_executed is too large to fit in the response.
        /// 
        /// </value>
        ///
        public enum GtidSetTypeEnum {
            [EnumMember(Value = "GTID_EXECUTED")]
            GtidExecuted,
            [EnumMember(Value = "GTID_AVAILABLE")]
            GtidAvailable
        };

        /// <value>
        /// Specifies whether to collect the full set of GTIDs executed on the DB System 
        /// ([gtid_executed](https://dev.mysql.com/doc/en/replication-options-gtids.html#sysvar_gtid_executed)) 
        /// or the set of GTIDs available in the DB System binary logs, not part of
        /// ([gtid_purged](https://dev.mysql.com/doc/en/replication-options-gtids.html#sysvar_gtid_purged)) 
        /// (GTID_AVAILABLE, which is gtid_executed - gtid_purged).
        /// Use GTID_AVAILABLE if gtid_executed is too large to fit in the response.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "gtidSetType")]
        [JsonConverter(typeof(StringEnumConverter))]
        public System.Nullable<GtidSetTypeEnum> GtidSetType { get; set; }
        
        /// <value>
        /// Specifies the GTID set to be checked on the DB System to determine whether it has been applied. The result of 
        /// the check is isGtidSetApplied in the response.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "gtidSetToApply")]
        public string GtidSetToApply { get; set; }
        
        /// <value>
        /// List of Channel IDs for which to collect status information.
        /// </value>
        [JsonProperty(PropertyName = "channelIds")]
        public System.Collections.Generic.List<string> ChannelIds { get; set; }
        
    }
}
