/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.MysqlService.Models
{
    /// <summary>
    /// The details of a maintenance event.
    /// 
    /// </summary>
    public class MaintenanceEvent 
    {
        
        /// <value>
        /// The OCID of the DB System this maintenance event is associated with.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "DbSystemId is required.")]
        [JsonProperty(PropertyName = "dbSystemId")]
        public string DbSystemId { get; set; }
        
        /// <value>
        /// The OCID of the compartment the maintenance event belongs to.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "CompartmentId is required.")]
        [JsonProperty(PropertyName = "compartmentId")]
        public string CompartmentId { get; set; }
        
        /// <value>
        /// Information regarding what was performed during that maintenance.
        /// </value>
        [JsonProperty(PropertyName = "maintenanceNotes")]
        public string MaintenanceNotes { get; set; }
        
        /// <value>
        /// The date and time the record was created,
        /// as described by [RFC 3339](https://tools.ietf.org/rfc/rfc3339).
        /// 
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "TimeCreated is required.")]
        [JsonProperty(PropertyName = "timeCreated")]
        public System.Nullable<System.DateTime> TimeCreated { get; set; }
        
        /// <value>
        /// The date and time the maintenance event started,
        /// as described by [RFC 3339](https://tools.ietf.org/rfc/rfc3339).
        /// 
        /// </value>
        [JsonProperty(PropertyName = "timeStarted")]
        public System.Nullable<System.DateTime> TimeStarted { get; set; }
        
        /// <value>
        /// The date and time the maintenance event ended,
        /// as described by [RFC 3339](https://tools.ietf.org/rfc/rfc3339).
        /// 
        /// </value>
        [JsonProperty(PropertyName = "timeEnded")]
        public System.Nullable<System.DateTime> TimeEnded { get; set; }
        
        /// <value>
        /// The date and time the DB System was initially down during the maintenance,
        /// as described by [RFC 3339](https://tools.ietf.org/rfc/rfc3339).
        /// 
        /// </value>
        [JsonProperty(PropertyName = "timeMysqlSwitchOverStarted")]
        public System.Nullable<System.DateTime> TimeMysqlSwitchOverStarted { get; set; }
        
        /// <value>
        /// The date and time the DB System came back online during the maintenance,
        /// as described by [RFC 3339](https://tools.ietf.org/rfc/rfc3339).
        /// 
        /// </value>
        [JsonProperty(PropertyName = "timeMysqlSwitchOverEnded")]
        public System.Nullable<System.DateTime> TimeMysqlSwitchOverEnded { get; set; }
        
        /// <value>
        /// The MySQL version prior to the maintenance.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "MysqlVersionBeforeMaintenance is required.")]
        [JsonProperty(PropertyName = "mysqlVersionBeforeMaintenance")]
        public string MysqlVersionBeforeMaintenance { get; set; }
        
        /// <value>
        /// The MySQL version after the maintenance.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "MysqlVersionAfterMaintenance is required.")]
        [JsonProperty(PropertyName = "mysqlVersionAfterMaintenance")]
        public string MysqlVersionAfterMaintenance { get; set; }
        
        /// <value>
        /// The MySQL instances operated during a maintenance event.
        /// <br/>
        /// ALL:             maintenance event targeting all MySQL instances in a DB System.
        /// ALL_BUT_PRIMARY: maintenance event targeting all MySQL instances in a highly available DB System except the primary group member.
        /// PRIMARY_ONLY:    maintenance event targeting only the primary group member in a highly available DB System.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "maintenanceScope")]
        [JsonConverter(typeof(Oci.Common.Utils.ResponseEnumConverter))]
        public System.Nullable<MaintenanceScope> MaintenanceScope { get; set; }
        
        /// <value>
        /// How the maintenance event was triggered.
        /// <br/>
        /// AUTOMATIC:  maintenance event triggered as part of scheduled maintenance.
        /// MANUAL:     maintenance event triggered manually.
        /// SHAPE:      maintenance event triggered by a shape update.
        /// 
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "MaintenanceType is required.")]
        [JsonProperty(PropertyName = "maintenanceType")]
        [JsonConverter(typeof(Oci.Common.Utils.ResponseEnumConverter))]
        public System.Nullable<MaintenanceType> MaintenanceType { get; set; }
        
        /// <value>
        /// The nature of the maintenance event.
        /// <br/>
        /// DATABASE:  maintenance event causing a MySQL version upgrade. This may also include OS updates.
        /// OS_UPDATE: maintenance event causing an OS update.
        /// ONLINE_UPDATE: maintenance event causing downtime-free OS security patches.
        /// HARDWARE: hardware maintenance event affecting the DB System's VMs and BMs.
        /// 
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "MaintenanceAction is required.")]
        [JsonProperty(PropertyName = "maintenanceAction")]
        [JsonConverter(typeof(Oci.Common.Utils.ResponseEnumConverter))]
        public System.Nullable<MaintenanceAction> MaintenanceAction { get; set; }
                ///
        /// <value>
        /// The last status of the maintenance event.
        /// 
        /// </value>
        ///
        public enum MaintenanceStatusEnum {
            /// This value is used if a service returns a value for this enum that is not recognized by this version of the SDK.
            [EnumMember(Value = null)]
            UnknownEnumValue,
            [EnumMember(Value = "SUCCEEDED")]
            Succeeded,
            [EnumMember(Value = "FAILED")]
            Failed,
            [EnumMember(Value = "CANCELED")]
            Canceled
        };

        /// <value>
        /// The last status of the maintenance event.
        /// 
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "MaintenanceStatus is required.")]
        [JsonProperty(PropertyName = "maintenanceStatus")]
        [JsonConverter(typeof(Oci.Common.Utils.ResponseEnumConverter))]
        public System.Nullable<MaintenanceStatusEnum> MaintenanceStatus { get; set; }
        
    }
}
