/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.DesktopsService.Models
{
    /// <summary>
    /// Provides information about actions performed on a desktop, including type and time.
    /// </summary>
    public class DesktopAction 
    {
                ///
        /// <value>
        /// An action performed on a desktop.
        /// </value>
        ///
        public enum ActionEnum {
            /// This value is used if a service returns a value for this enum that is not recognized by this version of the SDK.
            [EnumMember(Value = null)]
            UnknownEnumValue,
            [EnumMember(Value = "API_START")]
            ApiStart,
            [EnumMember(Value = "API_STOP")]
            ApiStop,
            [EnumMember(Value = "AVAILABILITY_START")]
            AvailabilityStart,
            [EnumMember(Value = "AVAILABILITY_STOP")]
            AvailabilityStop,
            [EnumMember(Value = "DISCONNECTED_STOP")]
            DisconnectedStop,
            [EnumMember(Value = "DISCONNECTED_DELETE")]
            DisconnectedDelete,
            [EnumMember(Value = "SCHEDULED_START")]
            ScheduledStart,
            [EnumMember(Value = "SCHEDULED_STOP")]
            ScheduledStop,
            [EnumMember(Value = "SYNCHRONIZE")]
            Synchronize,
            [EnumMember(Value = "CONNECTED")]
            Connected,
            [EnumMember(Value = "DISCONNECTED")]
            Disconnected
        };

        /// <value>
        /// An action performed on a desktop.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "Action is required.")]
        [JsonProperty(PropertyName = "action")]
        [JsonConverter(typeof(Oci.Common.Utils.ResponseEnumConverter))]
        public System.Nullable<ActionEnum> Action { get; set; }
        
        /// <value>
        /// The time of an action performed on a desktop.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "TimeApplied is required.")]
        [JsonProperty(PropertyName = "timeApplied")]
        public System.Nullable<System.DateTime> TimeApplied { get; set; }
        
    }
}
