/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.DatabasetoolsService.Models
{
    /// <summary>
    /// The details of an MCP server endpoint.
    /// </summary>
    public class DatabaseToolsMcpServerEndpoint 
    {
        
        /// <value>
        /// The MCP server type
        /// </value>
        [JsonProperty(PropertyName = "type")]
        [JsonConverter(typeof(Oci.Common.Utils.ResponseEnumConverter))]
        public System.Nullable<DatabaseToolsMcpServerType> Type { get; set; }
        
        /// <value>
        /// The URI endpoint of the MCP server
        /// </value>
        [JsonProperty(PropertyName = "endpoint")]
        public string Endpoint { get; set; }
        
    }
}
