/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.DatabasetoolsService.Models
{
    /// <summary>
    /// Database Tools MCP Toolset information to be updated for the CUSTOM_SQL_TOOL type.
    /// </summary>
    public class UpdateDatabaseToolsMcpToolsetCustomSqlToolDetails : UpdateDatabaseToolsMcpToolsetDetails
    {
        
        /// <value>
        /// Instructions describing how to use the MCP toolset and its features. This can be used to improve the LLM's understanding of the tool.
        /// </value>
        [JsonProperty(PropertyName = "toolDescription")]
        public string ToolDescription { get; set; }
        
        /// <value>
        /// Name of the tool returned by the MCP Server
        /// </value>
        [JsonProperty(PropertyName = "toolName")]
        public string ToolName { get; set; }
        
        [JsonProperty(PropertyName = "source")]
        public DatabaseToolsCustomSqlToolToolsetSource Source { get; set; }
        
        /// <value>
        /// The variables to use with the query
        /// </value>
        [JsonProperty(PropertyName = "variables")]
        public System.Collections.Generic.List<DatabaseToolsMcpToolsetCustomSqlToolVariable> Variables { get; set; }
        
        /// <value>
        /// The roles granted access to the MCP tool generated by this toolset
        /// </value>
        [JsonProperty(PropertyName = "allowedRoles")]
        public System.Collections.Generic.List<string> AllowedRoles { get; set; }
        
        /// <value>
        /// The default execution type for the toolset. The default value is SYNCHRONOUS.
        /// <br/>
        /// To use ASYNCHRONOUS execution, the MCP Server must have the storage property configured.
        /// 
        /// </value>
        [JsonProperty(PropertyName = "defaultExecutionType")]
        [JsonConverter(typeof(StringEnumConverter))]
        public System.Nullable<DatabaseToolsMcpToolsetDefaultExecutionType> DefaultExecutionType { get; set; }
        
        [JsonProperty(PropertyName = "type")]
        private readonly string type = "CUSTOM_SQL_TOOL";
    }
}
