/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace Oci.DatabasetoolsService.Models
{
    /// <summary>
    /// Database Tools SQL report information to be updated.
    /// </summary>
    [JsonConverter(typeof(UpdateDatabaseToolsSqlReportDetailsModelConverter))]
    public class UpdateDatabaseToolsSqlReportDetails 
    {
        
        /// <value>
        /// A user-friendly name. Does not have to be unique and can be updated. Avoid entering confidential information.
        /// </value>
        [JsonProperty(PropertyName = "displayName")]
        public string DisplayName { get; set; }
        
        /// <value>
        /// Defined tags for this resource. Each key is predefined and scoped to a namespace.
        /// Example: {&quot;foo-namespace&quot;: {&quot;bar-key&quot;: &quot;value&quot;}}
        /// </value>
        [JsonProperty(PropertyName = "definedTags")]
        public System.Collections.Generic.Dictionary<string, System.Collections.Generic.Dictionary<string, System.Object>> DefinedTags { get; set; }
        
        /// <value>
        /// Simple key-value pair that is applied without any predefined name, type or scope. Exists for cross-compatibility only.
        /// Example: {&quot;bar-key&quot;: &quot;value&quot;}
        /// </value>
        [JsonProperty(PropertyName = "freeformTags")]
        public System.Collections.Generic.Dictionary<string, string> FreeformTags { get; set; }
        
        
        /// <value>
        /// SQL query executed to generate the report.
        /// </value>
        [JsonProperty(PropertyName = "source")]
        public string Source { get; set; }
        
        /// <value>
        /// A description of the SQL report.
        /// </value>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }
        
        /// <value>
        /// Purpose of the Database Tools SQL report. Scenario or conditions describing when or why this report should be used. Provides selection criteria to AI agents to improve report selection accuracy.
        /// </value>
        [JsonProperty(PropertyName = "purpose")]
        public string Purpose { get; set; }
        
        /// <value>
        /// Instructions on how to use the SQL report. Step-by-step guidance for an AI agent on how to execute or fill in parameters for the report.
        /// </value>
        [JsonProperty(PropertyName = "instructions")]
        public string Instructions { get; set; }
        
        /// <value>
        /// Variables referenced in the Database Tools SQL Report source.
        /// </value>
        [JsonProperty(PropertyName = "variables")]
        public System.Collections.Generic.List<DatabaseToolsSqlReportVariable> Variables { get; set; }
        
        /// <value>
        /// Descriptive information on columns referenced in the Database Tools SQL Report source.
        /// </value>
        [JsonProperty(PropertyName = "columns")]
        public System.Collections.Generic.List<DatabaseToolsSqlReportColumn> Columns { get; set; }
        
    }

    public class UpdateDatabaseToolsSqlReportDetailsModelConverter : JsonConverter
    {
        public override bool CanWrite => false;
        public override bool CanRead => true;
        public override bool CanConvert(System.Type type)
        {
            return type == typeof(UpdateDatabaseToolsSqlReportDetails);
        }
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            throw new System.InvalidOperationException("Use default serialization.");
        }

        public override object ReadJson(JsonReader reader, System.Type objectType, object existingValue, JsonSerializer serializer)
        {
            var jsonObject = JObject.Load(reader);
            var obj = default(UpdateDatabaseToolsSqlReportDetails);
            var discriminator = jsonObject["type"].Value<string>();
            switch (discriminator)
            {
                case "ORACLE_DATABASE":
                    obj = new UpdateDatabaseToolsSqlReportDetailsOracleDatabase();
                    break;
            }
            serializer.Populate(jsonObject.CreateReader(), obj);
            return obj;
        }
    }
}
